### ISSUE TITLE
能让他兼容IE吗 | IE compatiable issue

### ISSUE THREAD

**Issue by rhinonan** [pd4d10/hashmd#1]
svelte 编译后的代码貌似稍微处理一下就行了，他没有使用像Vue一样无法转化的语言特性。

**Comment by pd4d10** [comment]
感谢反馈，最新的版本 v1.1.0 中已经加入 es5 的包，可以支持到 IE9

示例：https://github.com/bytedance/bytemd/blob/main/examples/legacy-browser/index.html

---

ES5 bundle has been added to the latest version v1.1.0, which supports IE9+

Example: https://github.com/bytedance/bytemd/blob/main/examples/legacy-browser/index.html
