### ISSUE TITLE
The editor cannot be used in a production environment of Vite

### ISSUE THREAD

**Issue by sufengyong** [pd4d10/hashmd#108]
Initialize an app with vite and then use the editor in production, and you'll see a console error.The error message looks like the result of a circular dependency.

**Comment by ZirionNeft** [comment]
Seems that issue is related for:
syntax-tree/hast-util-to-html#22
syntax-tree/mdast-util-to-hast#55

**Comment by ZirionNeft** [comment]
My temporary workaround of this issue until the original package is updated.
Add these lines into resolutions block of your package.json and all should work fine
```json
"resolutions": {
  "mdast-util-to-hast": "github:SQReder/mdast-util-to-hast#10.2.1",
  "hast-util-to-html": "github:ZirionNeft/hast-util-to-html#7.1.4"
}
```

**Comment by gomeslucasm** [comment]
i'm working around with the same error, any updates about it?

**Comment by yonnic** [comment]
this library finally fixed the issue and by this code i could finally run it too

```javascript
 "resolutions": {
    "mdast-util-to-hast": "github:syntax-tree/mdast-util-to-hast#11.2.1",
    "hast-util-to-html": "github:syntax-tree/hast-util-to-html#8.0.2"
  }
```

**Comment by pd4d10** [comment]
Thanks for your report! And also @ZirionNeft 's answer

Are there still problems?

**Comment by rockeodear** [comment]
That happened to me, too

**Comment by pd4d10** [comment]
Hi, this issue should have been fixed with the latest version.
