### ISSUE TITLE
图片不能使用base64的吗？使用base64图片不能显示？

### ISSUE THREAD

**Issue by hyy0316** [pd4d10/hashmd#110]
![arrow-down-bold.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAdElEQVQ4T92SQQ6AIAwEh5/py9SXydPMJtYQbakJFyMXEroMbLeFwVUG7/MdwHRaqS8tXXqzoIMd2IA1gai+ADNQ2x5YoQd5aO5NNIF2gdrlPuCl4EHC30UxthBp5Nm11psDg8hG2JdskCyRMJkMkI7FDwAHGVkYEZtbU38AAAAASUVORK5CYII=)

![image](https://user-images.githubusercontent.com/56791680/126601370-7f246e70-5bb8-4de5-b107-50885497ecbb.png)

**Comment by hyy0316** [comment]
(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAdElEQVQ4T92SQQ6AIAwEh5/py9SXydPMJtYQbakJFyMXEroMbLeFwVUG7/MdwHRaqS8tXXqzoIMd2IA1gai+ADNQ2x5YoQd5aO5NNIF2gdrlPuCl4EHC30UxthBp5Nm11psDg8hG2JdskCyRMJkMkI7FDwAHGVkYEZtbU38AAAAASUVORK5CYII=)

**Comment by pd4d10** [comment]
The sanitize could be customized if you want to change the default behavior:

```js
const sanitize = (schema) => {
  schema.protocols.src.push('data')
  return schema
}

<Editor
  // ...
  sanitize={sanitize}
/>

**Comment by hyy0316** [comment]
thank! 已解决 

> The sanitize could be customized if you want to change the default behavior:
> 
> ```js
> const sanitize = (schema) => {
>   schema.protocols.src.push('data')
>   return schema
> }
> 
> <Editor
>   // ...
>   sanitize={sanitize}
> />
> ```



> The sanitize could be customized if you want to change the default behavior:
> 
> ```js
> const sanitize = (schema) => {
>   schema.protocols.src.push('data')
>   return schema
> }
> 
> <Editor
>   // ...
>   sanitize={sanitize}
> />
> ```
