### ISSUE TITLE
请问使用公式会出现重复渲染问题要怎么解决呢？

### ISSUE THREAD

**Issue by hyy0316** [pd4d10/hashmd#111]
![微信图片_20210723171832](https://user-images.githubusercontent.com/56791680/126762645-649593ea-a14a-4fef-8215-4ce0789d3fa4.png)
![微信截图_20210723164818](https://user-images.githubusercontent.com/56791680/126762674-2441a0fd-44e8-4e95-b70b-3844e72065c5.png)

**Comment by pd4d10** [comment]
Could you provide a reproduction, for example, https://codesandbox.io/?

**Comment by hyy0316** [comment]
已解决，由于同时引用了@bytemd/plugin-math和@bytemd/plugin-math-ssr,部分项目只支持其中一种
