### ISSUE TITLE
Bytemd not working in svelte kit project

### ISSUE THREAD

**Issue by praveenkpatare** [pd4d10/hashmd#112]
Hello all,

I am working on a project which uses SvelteKit framweork.
I am using the ByteMd library for using a text editor in my project.
However when i try to import the library in the script tag, it throws an unexpected token error for this import - 
import gfm '@bytemd/plugin-gfm';

How do i resolve this. Please advise.

Thanks in advance.

**Comment by pd4d10** [comment]
Could you please provide a reproduce repo?

**Comment by sswatson** [comment]
Looks like you're missing the `from` keyword:

```js
import gfm from '@bytemd/plugin-gfm';
```

**Comment by axmad386** [comment]
I think this is the same issue #96

**Comment by pd4d10** [comment]
Thanks for the report!

Let's track this issue with #96.
