### ISSUE TITLE
Is it possible to implement WYSIWYG Mode in current architeature ？

### ISSUE THREAD

**Issue by linonetwo** [pd4d10/hashmd#113]
Just like hyperMD or slatejs?

Is there a limitation in the current architecture?

**Comment by pd4d10** [comment]
I think we may reuse the plugin system, but the implementations are basically different.

**Comment by linonetwo** [comment]
Use [https://github.com/ianstormtaylor/slate](https://github.com/ianstormtaylor/slate) and [https://github.com/udecode/plate](https://github.com/udecode/plate) instead.
