### ISSUE TITLE
请支持自定义toolbar

### ISSUE THREAD

**Issue by codingcn** [pd4d10/hashmd#114]
很多人都有这个需求，但貌似bytemd并没有提供相应的API

**Comment by dmwin72015** [comment]
要啥子自行车

> 很多人都有这个需求，但貌似bytemd并没有提供相应的API

**Comment by dmwin72015** [comment]
@xxx
- [x] 1
- [x] 2
- [x] 3

**Comment by dmwin72015** [comment]
> 要啥子自行车
> 
> > 很多人都有这个需求，但貌似bytemd并没有提供相应的API

其实我也想要自行车

**Comment by 0xinhua** [comment]
> 很多人都有这个需求，但貌似bytemd并没有提供相应的API

@codingcn 具体是怎样的需求？目前是支持新增自定义 toolbar 工具的，可以参考代码https://github.com/bytedance/bytemd/blob/main/packages/bytemd/src/toolbar.svelte#L69 在 plugins 中自行设置 actions 对象

**Comment by TunnelHunter** [comment]
@M1seRy 就很简单的一个场景。把右侧tab的倒数两个tab去掉。用户该如何操作？

**Comment by dmwin72015** [comment]
> @M1seRy 就很简单的一个场景。把右侧tab的倒数两个tab去掉。用户该如何操作？

同问，图片可以上传，也可以输入网络地址，怎么操作

**Comment by hongfaqiu** [comment]
> @M1sery 就很简单的一个场景。把右侧tab的倒数两个tab去掉。用户该如何操作？

可以用css控制https://github.com/bytedance/bytemd/issues/92#issuecomment-1113470854
