### ISSUE TITLE
footnotes，怎么修改鼠标移上时a标签的href路径

### ISSUE THREAD

**Issue by hyy0316** [pd4d10/hashmd#115]
![Snipaste_2021-08-06_17-54-46](https://user-images.githubusercontent.com/56791680/128493130-bba942fd-df6a-450e-adc1-2a199fae73aa.png)
问题描述：
1.当前页面的路由为，http://localhost:3000/#/counter，
2.当鼠标悬停在footnotes的link上时，跳转的路径均为默认路径，如http://localhost:3000/#fnref-bignote
期望：
我要怎么阻止href的跳转，只能通过DOM操作吗？怎么自定义footnotes link的跳转

**Comment by curly210102** [comment]
你好，如果另你困扰的是 footnotes 跳转会干扰路由运作，把 HashRouter 换成 BrowserRouter 或许是更合适的解决方法。
该问题产生的原因是 HashRouter 依赖 window.location.hash 来实现路由切换，使用 HashRouter 意味着需要避免使用文章内跳转，比如标题跳转、注脚跳转。

如果实在无法切换成 BrowserRouter，相较于 DOM 操作，建议加入 remark 插件或 rehype 插件来实现自定义功能，比如在 [remark-unlink](https://github.com/remarkjs/remark-unlink/blob/main/index.js) 插件的基础上改造一下。
