### ISSUE TITLE
Will mdx support be added?

### ISSUE THREAD

**Issue by so1ve** [pd4d10/hashmd#116]
As far as I know, the mdx plug-in existed for some time, and was later deleted in a commit, and there was never a document.
I personally think that adding mdx support can greatly improve the degree of freedom of bytemd and adapt to more scenarios.
Have you considered supporting mdx at present?
Thank you!

**Comment by pd4d10** [comment]
Yeah, it's expected to be integrated, but the problem is that MDX itself is too tightly coupled with React.

So there's a bit more to think about the integrated way. And of course, if you have any idea, feel free to discuss it here
