### ISSUE TITLE
AnyOne is using bytemd in React?

### ISSUE THREAD

**Issue by Jansora** [pd4d10/hashmd#12]
Are there any demo for using bytemd and plugins in React? i have tried it, with some error. who can help me? thank you.

https://codesandbox.io/s/condescending-lake-pes4x?file=/src/App.js

**Comment by pd4d10** [comment]
In your example, the `image` plugin has a required options: `upload`. Try

```js
image({
  async upload(files) {
    // TODO: upload image files and return urls
    return ['url']
  }
})
```

**Comment by Jansora** [comment]
Ok. thank you
