### ISSUE TITLE
The form cannot be expressed

### ISSUE THREAD

**Issue by lin-mt** [pd4d10/hashmd#122]
create app by `npx create-react-app`

App.tsx

```typescript
import React, {useState} from 'react';
import 'bytemd/dist/index.min.css'
import {Editor} from '@bytemd/react';
import gfm from '@bytemd/plugin-gfm';

const plugins = [
  gfm(),
]

function App() {

  const [value, setValue] = useState<string>('')

  return (
    <div style={{margin: 100}}>
      <Editor
        value={value}
        plugins={plugins}
        onChange={(v) => {
          setValue(v);
        }}
      />
    </div>
  );
}

export default App;
```

Result:

![image](https://user-images.githubusercontent.com/58337359/132653228-b696bbbd-7828-49c6-8da7-57fe86e94475.png)

**Comment by curly210102** [comment]
> There is no built-in styles for the Viewer. You could use third-party markdown themes, for example juejin-markdown-themes and github-markdown-css.
reference: https://github.com/bytedance/bytemd#viewer-1

You need import markdown theme css file.

**Comment by lin-mt** [comment]
> > There is no built-in styles for the Viewer. You could use third-party markdown themes, for example juejin-markdown-themes and github-markdown-css.
> > reference: https://github.com/bytedance/bytemd#viewer-1
> 
> You need import markdown theme css file.

Is there anything else besides importing this `import 'bytemd/dist/index.min.css'`?

**Comment by lin-mt** [comment]
> > There is no built-in styles for the Viewer. You could use third-party markdown themes, for example juejin-markdown-themes and github-markdown-css.
> > reference: https://github.com/bytedance/bytemd#viewer-1
> 
> You need import markdown theme css file.

yes ! it works. thx
