### ISSUE TITLE
the document is too simple, show my demo.

### ISSUE THREAD

**Issue by hsxyhao** [pd4d10/hashmd#126]
The demo is same as [this](https://bytemd.netlify.app/).
> if you enable math plugin, you should add `import 'katex/dist/katex.css'` at main.js
```vue
<template>
    <ByteMd ref="editor" :value="value" :locale="zhHans" :plugins="plugins" :editorConfig="editorConfig" @change="handleChange" />
</template>
<script>
import ByteMd from '@bytemd/vue'
import breaks from '@bytemd/plugin-breaks'
import footnotes from '@bytemd/plugin-footnotes'
import frontmatter from '@bytemd/plugin-frontmatter'
import gemoji from '@bytemd/plugin-gemoji'
import gfm from '@bytemd/plugin-gfm'
import highlight from '@bytemd/plugin-highlight'
import math from '@bytemd/plugin-math'
import mermaid from '@bytemd/plugin-mermaid'
import mediumZoom from '@bytemd/plugin-medium-zoom'
import zhHans from 'bytemd/lib/locales/zh_Hans.json'
import mermaid_zhHans from '@bytemd/plugin-mermaid/lib/locales/zh_Hans.json'
import math_zhHans from '@bytemd/plugin-math/lib/locales/zh_Hans.json'
import gfm_zhHans from '@bytemd/plugin-gfm/lib/locales/zh_Hans.json'

const plugins = [
    breaks(),
    footnotes(),
    frontmatter(),
    gemoji(),
    gfm({locale: gfm_zhHans}),
    highlight(),
    math({locale: math_zhHans}),
    mermaid({locale: mermaid_zhHans}),
    mediumZoom()
]

const editorConfig = {
    lineNumbers: true
}

export default {
    components: { ByteMd },
    data() {
        return { 
            value: '', 
            plugins, 
            editorConfig,
            zhHans
        }
    },
    methods: {
        handleChange(v) {
            this.value = v;
        }
    }
}
</script>
```

**Comment by lin-mt** [comment]
> ```
> editorConfig
> ```

Is there an example of React?

**Comment by lin-mt** [comment]
> The demo is same as [this](https://bytemd.netlify.app/).
> 
> > if you enable math plugin, you should add `import 'katex/dist/katex.css'` at main.js
> 
> ```
> <template>
>     <ByteMd ref="editor" :value="value" :locale="zhHans" :plugins="plugins" :editorConfig="editorConfig" @change="handleChange" />
> </template>
> <script>
> import ByteMd from '@bytemd/vue'
> import breaks from '@bytemd/plugin-breaks'
> import footnotes from '@bytemd/plugin-footnotes'
> import frontmatter from '@bytemd/plugin-frontmatter'
> import gemoji from '@bytemd/plugin-gemoji'
> import gfm from '@bytemd/plugin-gfm'
> import highlight from '@bytemd/plugin-highlight'
> import math from '@bytemd/plugin-math'
> import mermaid from '@bytemd/plugin-mermaid'
> import mediumZoom from '@bytemd/plugin-medium-zoom'
> import zhHans from 'bytemd/lib/locales/zh_Hans.json'
> import mermaid_zhHans from '@bytemd/plugin-mermaid/lib/locales/zh_Hans.json'
> import math_zhHans from '@bytemd/plugin-math/lib/locales/zh_Hans.json'
> import gfm_zhHans from '@bytemd/plugin-gfm/lib/locales/zh_Hans.json'
> 
> const plugins = [
>     breaks(),
>     footnotes(),
>     frontmatter(),
>     gemoji(),
>     gfm({locale: gfm_zhHans}),
>     highlight(),
>     math({locale: math_zhHans}),
>     mermaid({locale: mermaid_zhHans}),
>     mediumZoom()
> ]
> 
> const editorConfig = {
>     lineNumbers: true
> }
> 
> export default {
>     components: { ByteMd },
>     data() {
>         return { 
>             value: '', 
>             plugins, 
>             editorConfig,
>             zhHans
>         }
>     },
>     methods: {
>         handleChange(v) {
>             this.value = v;
>         }
>     }
> }
> </script>
> ```

Is there an example of React?

**Comment by yijinc** [comment]
> > The demo is same as [this](https://bytemd.netlify.app/).
> > > if you enable math plugin, you should add `import 'katex/dist/katex.css'` at main.js
> > 
> > 
> > ```
> > <template>
> >     <ByteMd ref="editor" :value="value" :locale="zhHans" :plugins="plugins" :editorConfig="editorConfig" @change="handleChange" />
> > </template>
> > <script>
> > import ByteMd from '@bytemd/vue'
> > import breaks from '@bytemd/plugin-breaks'
> > import footnotes from '@bytemd/plugin-footnotes'
> > import frontmatter from '@bytemd/plugin-frontmatter'
> > import gemoji from '@bytemd/plugin-gemoji'
> > import gfm from '@bytemd/plugin-gfm'
> > import highlight from '@bytemd/plugin-highlight'
> > import math from '@bytemd/plugin-math'
> > import mermaid from '@bytemd/plugin-mermaid'
> > import mediumZoom from '@bytemd/plugin-medium-zoom'
> > import zhHans from 'bytemd/lib/locales/zh_Hans.json'
> > import mermaid_zhHans from '@bytemd/plugin-mermaid/lib/locales/zh_Hans.json'
> > import math_zhHans from '@bytemd/plugin-math/lib/locales/zh_Hans.json'
> > import gfm_zhHans from '@bytemd/plugin-gfm/lib/locales/zh_Hans.json'
> > 
> > const plugins = [
> >     breaks(),
> >     footnotes(),
> >     frontmatter(),
> >     gemoji(),
> >     gfm({locale: gfm_zhHans}),
> >     highlight(),
> >     math({locale: math_zhHans}),
> >     mermaid({locale: mermaid_zhHans}),
> >     mediumZoom()
> > ]
> > 
> > const editorConfig = {
> >     lineNumbers: true
> > }
> > 
> > export default {
> >     components: { ByteMd },
> >     data() {
> >         return { 
> >             value: '', 
> >             plugins, 
> >             editorConfig,
> >             zhHans
> >         }
> >     },
> >     methods: {
> >         handleChange(v) {
> >             this.value = v;
> >         }
> >     }
> > }
> > </script>
> > ```
> 
> Is there an example of React?

``

> > The demo is same as [this](https://bytemd.netlify.app/).
> > > if you enable math plugin, you should add `import 'katex/dist/katex.css'` at main.js
> > 
> > 
> > ```
> > <template>
> >     <ByteMd ref="editor" :value="value" :locale="zhHans" :plugins="plugins" :editorConfig="editorConfig" @change="handleChange" />
> > </template>
> > <script>
> > import ByteMd from '@bytemd/vue'
> > import breaks from '@bytemd/plugin-breaks'
> > import footnotes from '@bytemd/plugin-footnotes'
> > import frontmatter from '@bytemd/plugin-frontmatter'
> > import gemoji from '@bytemd/plugin-gemoji'
> > import gfm from '@bytemd/plugin-gfm'
> > import highlight from '@bytemd/plugin-highlight'
> > import math from '@bytemd/plugin-math'
> > import mermaid from '@bytemd/plugin-mermaid'
> > import mediumZoom from '@bytemd/plugin-medium-zoom'
> > import zhHans from 'bytemd/lib/locales/zh_Hans.json'
> > import mermaid_zhHans from '@bytemd/plugin-mermaid/lib/locales/zh_Hans.json'
> > import math_zhHans from '@bytemd/plugin-math/lib/locales/zh_Hans.json'
> > import gfm_zhHans from '@bytemd/plugin-gfm/lib/locales/zh_Hans.json'
> > 
> > const plugins = [
> >     breaks(),
> >     footnotes(),
> >     frontmatter(),
> >     gemoji(),
> >     gfm({locale: gfm_zhHans}),
> >     highlight(),
> >     math({locale: math_zhHans}),
> >     mermaid({locale: mermaid_zhHans}),
> >     mediumZoom()
> > ]
> > 
> > const editorConfig = {
> >     lineNumbers: true
> > }
> > 
> > export default {
> >     components: { ByteMd },
> >     data() {
> >         return { 
> >             value: '', 
> >             plugins, 
> >             editorConfig,
> >             zhHans
> >         }
> >     },
> >     methods: {
> >         handleChange(v) {
> >             this.value = v;
> >         }
> >     }
> > }
> > </script>
> > ```
> 
> Is there an example of React?

```javascript
import React, { useLayoutEffect, useRef, useState } from 'react';
import { Affix } from 'antd';
import { Viewer } from '@bytemd/react';
import breaks from '@bytemd/plugin-breaks';
import footnotes from '@bytemd/plugin-footnotes';
import frontmatter from '@bytemd/plugin-frontmatter'; // 头部元信息
import gemoji from '@bytemd/plugin-gemoji'; // emoji😊 代码
import gfm from '@bytemd/plugin-gfm'; // 超链接、删除线、表格、任务列表
import highlight from '@bytemd/plugin-highlight';
import math from '@bytemd/plugin-math'; // 数学公式
import 'katex/dist/katex.min.css'; // for plugin-math
import mediumZoom from '@bytemd/plugin-medium-zoom';
import mermaid from '@bytemd/plugin-mermaid'; // 图表 / 流程图
import 'bytemd/dist/index.min.css'; // bytemd 基础样式
import 'juejin-markdown-themes/dist/juejin.css'; // md theme

import styles from './styles.less';

const plugins = [
  breaks(),
  footnotes(),
  frontmatter(),
  gemoji(),
  gfm(),
  highlight(),
  math(),
  mediumZoom(),
  mermaid(),
];

type IProps = {
  value: string;
};

type Item = { level: number; text: string };

export default ({ value }: IProps) => {
  const ref = useRef<HTMLDivElement>(null);
  const [items, setItems] = useState<Item[]>([]);
  const [minLevel, setMinLevel] = useState<number>(6);
  const [currentHeadingIndex, setCurrentHeadingIndex] = useState<number>(0);

  useLayoutEffect(() => {
    const root = (ref.current as HTMLElement).querySelector('.markdown-body') as HTMLElement;

    /**
     * init table of content
     * refer to bytemd/packages/bytemd/src/toc.svelte
     **/
    const _items: Item[] = [];
    let _minLevel = minLevel;
    // root.children is HTMLCollection
    Array.prototype.filter.call(root.children, (v) => v && v.nodeType === 1).forEach((node: HTMLElement, index) => {
      if (node.tagName[0].toLowerCase() === 'h' && (node.hasChildNodes())) {
          const i = Number(node.tagName[1]); // h1 h2 h3 h4 h5 h6
          _minLevel = Math.min(_minLevel, i)
          _items.push({
            level: i,
            text: node.innerText, // stringifyHeading(node),
          })
        }
    })
    setMinLevel(_minLevel);
    setItems(_items);

  }, [value]);

  useLayoutEffect(() => {

    const root = (ref.current as HTMLElement).querySelector('.markdown-body') as HTMLElement;
    const headings = root.querySelectorAll('h1,h2,h3,h4,h5,h6');

    const observer = new IntersectionObserver((entries: IntersectionObserverEntry[]) => {
      const io: IntersectionObserverEntry = entries[0];
      if(io.isIntersecting === true) {
        const index = Array.prototype.indexOf.call(headings, io.target);
        setCurrentHeadingIndex(preState => index);
      }
    }, { threshold: [1] });
    
    // observe all head
    headings.forEach(node => observer.observe(node));

    return () => {
      headings.forEach(node => observer.unobserve(node));
    }

  }, [value])

  const skipContent = (index: number) => {
    const root = (ref.current as HTMLElement).querySelector('.markdown-body') as HTMLElement;
    const headings = root.querySelectorAll('h1,h2,h3,h4,h5,h6');
    setCurrentHeadingIndex(index);
    headings[index].scrollIntoView();
  };

  return (
    <div className={styles.container} ref={ref}>
      <Viewer value={value} plugins={plugins} />
      {
        items.length > 0 && (
          <div className={styles.viewToc}>
            <Affix offsetTop={90}>
              <div className={styles.tocBox}>
                <ul className={styles.toc}>
                  {
                    items.map((item, index) => (
                      <li
                        key={String(index)}
                        className={`toc-${item.level}${currentHeadingIndex === index ? ' active': ''}`}
                        style={{ paddingLeft: (item.level - minLevel) * 16 + 8 }}
                        onClick={() => skipContent(index)}
                      >
                        {item.text}
                      </li>
                    ))
                  }
                </ul>
              </div>
            </Affix>
          </div>
        )
      }
    </div>
  )
}

```

`Viewer`没有现成的toc配置，自己简单实现了个😿

**Comment by lin-mt** [comment]
@yijinc 可以用👍，谢谢～！

**Comment by Coiggahou2002** [comment]
@hsxyhao 非常感谢你的demo！

**Comment by codingcn** [comment]
你们的lineNumbers设置了生效吗？

**Comment by wuye251** [comment]
有木有大佬用vue实现了toc层级结构
