### ISSUE TITLE
hightlight does not work

### ISSUE THREAD

**Issue by childrentime** [pd4d10/hashmd#128]
![image](https://user-images.githubusercontent.com/58261676/135223658-28caa23d-6832-45d9-82fe-153ed6833222.png)
![image](https://user-images.githubusercontent.com/58261676/135223706-3a691759-af95-497f-990c-2c9d72c20d59.png)
![image](https://user-images.githubusercontent.com/58261676/135223926-21584f4d-3c2e-4882-bece-b61c9a83ffe0.png)
![image](https://user-images.githubusercontent.com/58261676/135224039-686039a5-1b7d-45fb-954b-42579a264015.png)
 highlight的样式好像不生效 右边渲染出来的没有样式

**Comment by peachtang** [comment]
@childrentime 请问下你怎么解决的？我也遇到这个问题了

**Comment by childrentime** [comment]
@peachtang 要下载一个markdown主题引入 你可以下载掘金的或者github的 然后引入css

**Comment by peachtang** [comment]
@childrentime 可以提供下链接给我吗，谢谢了

**Comment by childrentime** [comment]
https://www.npmjs.com/package/github-markdown-css

**Comment by peachtang** [comment]
@childrentime 收到，感谢
