### ISSUE TITLE
是否可以直接在微信小程序页面上展示markdown?

### ISSUE THREAD

**Issue by carmel** [pd4d10/hashmd#129]
如题，想在微信小程序的页面上呈现bytemd输出的内容，不知是否可行。因为项目还没进行到这步，还未亲自验证，想提前问下，先谢了！

**Comment by curly210102** [comment]
是指借助 webview 显示？

**Comment by carmel** [comment]
不打算使用webview🙂

**Comment by curly210102** [comment]
那么应该是无法实现的，bytemd 编译的结果是 JS 进行 DOM 操作，但是小程序并没有提供 DOM API，因此无法直接运行。

> 小程序的逻辑层和渲染层是分开的，逻辑层运行在 JSCore 中，并没有一个完整浏览器对象，因而缺少相关的DOM API和BOM API。

可以借助 webview 跑一个一个包内 HTML 页面或者直接依托 remark 在小程序内实现 Preivew 效果（并不复杂）。

**Comment by carmel** [comment]
@curly210102 谢谢，了解啦！
