### ISSUE TITLE
如何将链接的a标签的target，改为_blank 😭 Do anyone know how to change the property of a tag

### ISSUE THREAD

**Issue by Lu-HuaiLiang** [pd4d10/hashmd#132]

**Comment by Jansora** [comment]
你用 js 配合 css 实现一个就好了啊

**Comment by Jansora** [comment]
给你参考下我写的锚点代码。
···
  const updateToc = () => {
    setTimeout(() => {
      const article = document.querySelector(".markdown-body");
      if(null == article || article.hasAttribute("querySelectorAll")) return;
      const hs = article.querySelectorAll("h1,h2,h3,h4,h5,h6");
      const Anchor = [];

      hs.forEach((item, index) => {
        const h = item.nodeName.substr(0, 2).toLowerCase()
        item.id = `Anchor-${h}-${index}`;
        Anchor.push({id: `Anchor-${h}-${index}`, text: item.textContent});
      })
      setAnchors(Anchor)
    }, 100);
  }
  const adminLoginStatus = AdminLoginStatus();
  const goto = (id) =>
      document.getElementById(id).scrollIntoView({
        block: "center",
        behavior: 'smooth'
      })
  useEffect(() => {
    updateToc()
  }, [note])
···

      {
        Anchors.map(anchor => {
          if(anchor.id[8] === "1") {
            return <Item key={anchor.id} onClick={() => goto(anchor.id)} > <Icon name="dot circle" /> {anchor.text} </Item>
          }
          return <SubItem key={anchor.id} onClick={() => goto(anchor.id)} > <Icon name="dot circle outline" /> {anchor.text} </SubItem>
        })
      }

**Comment by yijinc** [comment]
刚收到这个要求，我怀疑你是我领导😰

我这边直接简单粗暴处理了下

```javascript
useLayoutEffect(() => {
    const setAnchorTarget = () => {
      const root = (ref.current as HTMLElement).querySelector('.markdown-body') as HTMLElement;
      const anchors = root.querySelectorAll('a');
      anchors.forEach((a: HTMLAnchorElement) => a.target = '_blank');
    };
    setTimeout(setAnchorTarget);
  });
```

**Comment by 0xinhua** [comment]
@Lu-HuaiLiang 可尝试增加一个自定义viewer plugin ，如下：

```javascript
// hrefTargetPlugin.ts
import { BytemdPlugin } from 'bytemd';

export default function modifyHrefTarget(): BytemdPlugin {
  return {
    viewerEffect({ markdownBody }) {
      Array.from(markdownBody.querySelectorAll('a'))
        .filter((a) => {
          return Boolean(a.getAttribute('href'));
        })
        .forEach((a) => {
          a.setAttribute('target', '_blank');
        });
    },
  };
}

const viewerPlugins: BytemdPlugin[] = [
  ...yourPlugins,
  modifyHrefTarget(),
];

<Viewer {...props} plugins={viewerPlugins}  />

```

**Comment by wan-kong** [comment]
可以使用rehype的插件：[rehype-urls](https://github.com/brechtcs/rehype-urls)
```JavaScript
// customHrefTarget.js

import urls from "rehype-urls";
export default function customHrefTarget() {
  return {
    rehype: (u) =>
      u.use(urls, (url, node) => {
        if (Boolean(node.properties.href) == true) {
          node.properties.target = "_blank";
        }
      }),
  };
}
```
仅作参考-。-
感觉楼上老哥写的更方便一点

**Comment by ideaviewes** [comment]
@wan-kong ,rehype-urls不支持typescript
