### ISSUE TITLE
使用uploadImages方法时，文件上传至服务器，无法感知用户删除图片，会造成服务器脏数据。

### ISSUE THREAD

**Issue by TimmyYagami** [pd4d10/hashmd#134]
什么样的解决方式是解决这种问题的最优解呢？
 想法1： editor.$on('change'  监听并比较图片路径是否存在，不存在则删除
 想法2：表单提交时，比较所有markdown内容，不存在的图片就删除。
 
 两种方法似乎都不好，还有其他更优秀的解决方案吗？求教。

**Comment by pd4d10** [comment]
目前的策略是在导入图片时上传

这个需求是否可以理解为，希望编辑期间先暂存图片而不上传，在最后提交内容时拿到图片数据统一上传。

**Comment by jiangqiang1996** [comment]
直接图片转base64 就不存在你这个问题，只不过会有新的问题。
