### ISSUE TITLE
error to build ?

### ISSUE THREAD

**Issue by conanchen** [pd4d10/hashmd#138]
1. just clone bytemd repo
2. cd bytemd
3. yarn && yarn dev

got error: 

bytemd on  HEAD (21fffa2) [?] via  v16.13.1
✦3 ❯ yarn && yarn dev
yarn install v1.22.10
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[#############################------------------------------------------------------------------] 376/1215^C

bytemd on  HEAD (21fffa2) [?] via  v16.13.1 took 13s
✦3 ❯ git checkout master
error: pathspec 'master' did not match any file(s) known to git

bytemd on  HEAD (21fffa2) [?] via  v16.13.1
✦3 ❯ git branch
* (HEAD detached at v1.10.13)
  main

bytemd on  HEAD (21fffa2) [?] via  v16.13.1
✦3 ❯ git checkout mainm
error: pathspec 'mainm' did not match any file(s) known to git

bytemd on  HEAD (21fffa2) [?] via  v16.13.1
✦3 ❯ git checkout main
Previous HEAD position was 21fffa2 v1.10.13
Switched to branch 'main'
Your branch is up to date with 'origin/main'.

bytemd on  main [?] via  v16.13.1
✦3 ❯ yarn && yarn dev
yarn install v1.22.10
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "rollup-plugin-vue > @vue/component-compiler@4.2.4" has unmet peer dependency "postcss@>=6.0".
warning " > svelte-jester@1.8.2" has incorrect peer dependency "jest@<= 26".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ node scripts/postinstall.mjs
✨  Done in 68.99s.
yarn run v1.22.10
$ run-p dev:bundle dev:tsc dev:process
$ tsc --build --watch
$ rollup -cw
$ node scripts/process.mjs --watch
add /Users/CC/github/bytedance/bytemd/packages/vue/src/editor.vue
add /Users/CC/github/bytedance/bytemd/packages/vue/src/viewer.vue
add /Users/CC/github/bytedance/bytemd/packages/plugin-mermaid/src/locales/ca.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-mermaid/src/locales/en.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-mermaid/src/locales/es.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-mermaid/src/locales/fr.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-mermaid/src/locales/nb_NO.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-mermaid/src/locales/ru.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-mermaid/src/locales/zh_Hans.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales/ca.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales/en.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales/es.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales/fr.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales/ja.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales/nb_NO.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales/ru.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales/zh_Hans.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales/zh_Hant.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math/src/locales/ca.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math/src/locales/en.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math/src/locales/es.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math/src/locales/fr.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math/src/locales/ja.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math/src/locales/nb_NO.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math/src/locales/ru.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math/src/locales/zh_Hans.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-math/src/locales/zh_Hant.json
addDir /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/src/locales
add /Users/CC/github/bytedance/bytemd/packages/plugin-gfm/src/locales/ca.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-gfm/src/locales/en.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-gfm/src/locales/es.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-gfm/src/locales/fr.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-gfm/src/locales/nb_NO.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-gfm/src/locales/ru.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-gfm/src/locales/zh_Hans.json
add /Users/CC/github/bytedance/bytemd/packages/plugin-gfm/src/locales/zh_Hant.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/editor.svelte
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/help.svelte
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/status.svelte
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/toc.svelte
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/toolbar.svelte
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/viewer.svelte
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/ca.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/de.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/en.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/es.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/fr.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/ja.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/ko.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/nb_NO.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/ru.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/zh_Hans.json
add /Users/CC/github/bytedance/bytemd/packages/bytemd/src/locales/zh_Hant.json
[7:47:50 PM] Starting compilation in watch mode...

rollup v2.60.2
bundles packages/bytemd/styles/index.scss → style.js...
created style.js in 142ms
bundles packages/bytemd/styles/index.scss → style.js...
packages/bytemd/src/types.ts:1:32 - error TS2307: Cannot find module 'unified' or its corresponding type declarations.

1 import type { Processor } from 'unified'
                                 ~~~~~~~~~

packages/bytemd/src/types.ts:2:29 - error TS2307: Cannot find module 'hast-util-sanitize' or its corresponding type declarations.

2 import type { Schema } from 'hast-util-sanitize'
                              ~~~~~~~~~~~~~~~~~~~~

packages/bytemd/src/types.ts:3:28 - error TS2307: Cannot find module 'vfile' or its corresponding type declarations.

3 import type { VFile } from 'vfile'
                             ~~~~~~~

packages/bytemd/src/types.ts:4:50 - error TS2307: Cannot find module 'codemirror' or its corresponding type declarations.

4 import type { Editor, EditorConfiguration } from 'codemirror'
                                                   ~~~~~~~~~~~~

packages/bytemd/src/types.ts:5:29 - error TS2307: Cannot find module 'codemirror' or its corresponding type declarations.

5 import type CodeMirror from 'codemirror'
                              ~~~~~~~~~~~~

packages/bytemd/src/types.ts:8:28 - error TS2307: Cannot find module 'mdast' or its corresponding type declarations.

8 import type { Image } from 'mdast'
                             ~~~~~~~

packages/bytemd/src/editor.ts:1:39 - error TS2307: Cannot find module 'codemirror' or its corresponding type declarations.

1 import type { Editor, Position } from 'codemirror'
                                        ~~~~~~~~~~~~

packages/bytemd/src/editor.ts:2:29 - error TS2307: Cannot find module 'codemirror' or its corresponding type declarations.

2 import type CodeMirror from 'codemirror'
                              ~~~~~~~~~~~~

packages/bytemd/src/editor.ts:11:25 - error TS2307: Cannot find module 'select-files' or its corresponding type declarations.

11 import selectFiles from 'select-files'
                           ~~~~~~~~~~~~~~

packages/bytemd/src/utils.ts:1:21 - error TS2307: Cannot find module 'unified' or its corresponding type declarations.

1 import unified from 'unified'
                      ~~~~~~~~~

packages/bytemd/src/utils.ts:2:25 - error TS2307: Cannot find module 'remark-parse' or its corresponding type declarations.

2 import remarkParse from 'remark-parse'
                          ~~~~~~~~~~~~~~

packages/bytemd/src/utils.ts:3:26 - error TS2307: Cannot find module 'remark-rehype' or its corresponding type declarations.

3 import remarkRehype from 'remark-rehype'
                           ~~~~~~~~~~~~~~~

packages/bytemd/src/utils.ts:4:23 - error TS2307: Cannot find module 'rehype-raw' or its corresponding type declarations.

4 import rehypeRaw from 'rehype-raw'
                        ~~~~~~~~~~~~

packages/bytemd/src/utils.ts:5:28 - error TS2307: Cannot find module 'rehype-sanitize' or its corresponding type declarations.

5 import rehypeSanitize from 'rehype-sanitize'
                             ~~~~~~~~~~~~~~~~~

packages/bytemd/src/utils.ts:6:29 - error TS2307: Cannot find module 'rehype-stringify' or its corresponding type declarations.

6 import rehypeStringify from 'rehype-stringify'
                              ~~~~~~~~~~~~~~~~~~

packages/bytemd/src/utils.ts:7:22 - error TS2307: Cannot find module 'hast-util-sanitize/lib/github.json' or its corresponding type declarations.

7 import ghSchema from 'hast-util-sanitize/lib/github.json'
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/bytemd/src/utils.ts:8:29 - error TS2307: Cannot find module 'hast-util-sanitize' or its corresponding type declarations.

8 import type { Schema } from 'hast-util-sanitize'
                              ~~~~~~~~~~~~~~~~~~~~

[7:47:52 PM] Found 17 errors. Watching for file changes.

created style.js in 892ms
bundles /Users/CC/github/bytedance/bytemd/packages/bytemd/lib/index.js → packages/bytemd/dist/index.esm.js, packages/bytemd/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/bytemd/lib/index.js).
Error: Could not resolve entry module (packages/bytemd/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-breaks/lib/index.js → packages/plugin-breaks/dist/index.esm.js, packages/plugin-breaks/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-breaks/lib/index.js).
Error: Could not resolve entry module (packages/plugin-breaks/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-footnotes/lib/index.js → packages/plugin-footnotes/dist/index.esm.js, packages/plugin-footnotes/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-footnotes/lib/index.js).
Error: Could not resolve entry module (packages/plugin-footnotes/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-frontmatter/lib/index.js → packages/plugin-frontmatter/dist/index.esm.js, packages/plugin-frontmatter/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-frontmatter/lib/index.js).
Error: Could not resolve entry module (packages/plugin-frontmatter/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-gemoji/lib/index.js → packages/plugin-gemoji/dist/index.esm.js, packages/plugin-gemoji/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-gemoji/lib/index.js).
Error: Could not resolve entry module (packages/plugin-gemoji/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-gfm/lib/index.js → packages/plugin-gfm/dist/index.esm.js, packages/plugin-gfm/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-gfm/lib/index.js).
Error: Could not resolve entry module (packages/plugin-gfm/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-highlight/lib/index.js → packages/plugin-highlight/dist/index.esm.js, packages/plugin-highlight/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-highlight/lib/index.js).
Error: Could not resolve entry module (packages/plugin-highlight/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-highlight-ssr/lib/index.js → packages/plugin-highlight-ssr/dist/index.esm.js, packages/plugin-highlight-ssr/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-highlight-ssr/lib/index.js).
Error: Could not resolve entry module (packages/plugin-highlight-ssr/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-math/lib/index.js → packages/plugin-math/dist/index.esm.js, packages/plugin-math/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-math/lib/index.js).
Error: Could not resolve entry module (packages/plugin-math/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-math-ssr/lib/index.js → packages/plugin-math-ssr/dist/index.esm.js, packages/plugin-math-ssr/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-math-ssr/lib/index.js).
Error: Could not resolve entry module (packages/plugin-math-ssr/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-medium-zoom/lib/index.js → packages/plugin-medium-zoom/dist/index.esm.js, packages/plugin-medium-zoom/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-medium-zoom/lib/index.js).
Error: Could not resolve entry module (packages/plugin-medium-zoom/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/plugin-mermaid/lib/index.js → packages/plugin-mermaid/dist/index.esm.js, packages/plugin-mermaid/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/plugin-mermaid/lib/index.js).
Error: Could not resolve entry module (packages/plugin-mermaid/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/react/lib/index.js → packages/react/dist/index.esm.js, packages/react/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/react/lib/index.js).
Error: Could not resolve entry module (packages/react/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)

bundles /Users/CC/github/bytedance/bytemd/packages/vue/lib/index.js → packages/vue/dist/index.esm.js, packages/vue/dist/index.cjs.js...
[!] Error: Could not resolve entry module (packages/vue/lib/index.js).
Error: Could not resolve entry module (packages/vue/lib/index.js).
    at error (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/Users/CC/github/bytedance/bytemd/node_modules/rollup/dist/shared/rollup.js:22366:20)
    at async Promise.all (index 0)


[2021-12-02 19:47:52] waiting for changes...

**Comment by pd4d10** [comment]
This repo use pnpm. Could you try again with it?
