### ISSUE TITLE
react中onChange 里面只会拿到第一次值 更新值拿不到

### ISSUE THREAD

**Issue by zk0816** [pd4d10/hashmd#140]
在react使用Editor,定义了一个全局的对象 const [obj,setObj] = useState({title:'',content:''}), 在onChange中只能拿到data的默认初始值，当我在其他地方把title值修改了onchange 中 的title依然没发生改变，但是setObj却能照旧执行 并改变了obj值

**Comment by pd4d10** [comment]
根据描述看，是符合预期的

**Comment by pd4d10** [comment]
可以提供一个复现 repo
