### ISSUE TITLE
bytemd/react有性能问题

### ISSUE THREAD

**Issue by bosens-China** [pd4d10/hashmd#141]
如题，我有一个父组件，两个子组件，分为为Header和Content，现在我把所有状态提到父组件，通过props的形式进行传递，Header有一个格式化代码的操作。

现在问题来了，每次我改变content都会调用父组件传递的set方法，导致整个组件被更新，字数越多卡顿越严重

![image](https://user-images.githubusercontent.com/39508895/147314656-2aad689b-517d-4ec9-a4fa-80d5b1cbb3b8.png)

现在我想确认下，有什么办法可以进行一个优化吗。

**Comment by pd4d10** [comment]
根据描述看，似乎不是组件的问题。可以看下官方文档中 `useCallback` 部分
