### ISSUE TITLE
Switch to editing mode in just one paragraph

### ISSUE THREAD

**Issue by infogulch** [pd4d10/hashmd#143]
Basically the idea is a "paragraph editing" mode that you can switch to which reverts just the the currently selected paragraph back into unrendered markdown for editing, but leaves the rest of the document in a rendered state. This would make it easier to follow visually since only a small portion of the document would transition at once and switching back and forth would be less jarring. This might be a nice intermediate before going whole hog on a WYSIWYG editor as in #113 which would require basically a completely new edit/view mode implementation.

I think this could work because it's relatively simple to find the points where sections start and end in markdown (double newlines). Some implementation details that might need to be sussed out:

* Would need to introduce the concept of "selected paragraph" and a visual representation of it in view mode.
* Maybe (configurable?) hotkeys to switch between editing of the 'selected paragraph'
* Navigating between paragraphs with up/down arrow keys could automatically switch to edit the next paragraph. I suspect this would feel pretty slick.

Thoughts?

**Comment by pd4d10** [comment]
Sounds like a good idea, but I guess it would require some major changes in the architecture design.

It would be better if there are some prototypes for reference
