### ISSUE TITLE
vue导入bytemd 关于代码块的问题

### ISSUE THREAD

**Issue by abcdbdocker** [pd4d10/hashmd#146]
vue导入bytemd所有模块包括plugin-highlight但是只出现了代码高亮 并没有出现代码块,请问这个问题是怎么回事呢?是我姿势不对吗？
这是我
```js
const plugins = [
  gfm(),
  highlight(),
  mediumZoom(),
  gemoji(),
  frontmatter(),
  highlightSsr(),
  math(),
  mermaid(),
  breaks(),
  footnotes(),
  // Add more plugins here
]
```

**Comment by pd4d10** [comment]
1. highlight 与 highlightSsr 只需要其中一个即可
2. 界面看到效果，还需要引入 highlight.js 的 CSS 文件

**Comment by abcdbdocker** [comment]
我导入了 但是只能使用带底图的代码块,比如juejin的主题是没有代码块效果的,还有github主题也没有

**Comment by abcdbdocker** [comment]
另外还有一个问题 vue版本的bytemd 有上传文件插件吗?有demo吗？

**Comment by pd4d10** [comment]
React 和 Vue 版本的 `props` 都是一致的，可以参考 README.md 中的参数列表
