### ISSUE TITLE
关于把图片上传图标加载到工具栏中?

### ISSUE THREAD

**Issue by abcdbdocker** [pd4d10/hashmd#148]
![图片](https://user-images.githubusercontent.com/96030465/153812581-d37a1fdb-6e99-473b-b4be-03127fad72db.png)
![图片](https://user-images.githubusercontent.com/96030465/153812727-de0e01f2-5223-4435-8c9c-55827a34c901.png)

插件已经导入了，并且看了以前提的问题,都是说图片上传插件默认已经内部加载了,但是并没有说如何加载到工具栏中,是否有demo可以提供一样,我这里使用的是vue版本的，您提供的大部门demo都是react版本的,请问是否可以提供一下vue版本的demo?

**Comment by pd4d10** [comment]
似乎你用的不是最新版本？可以升级到最新版本试一下，上传图片默认会在工具栏中。

**Comment by abcdbdocker** [comment]
我是npm install  @bytemd/vue   并且您提供的也是1.10.13版本  还有比这个更新的吗？

**Comment by pd4d10** [comment]
你提供的截图有点奇怪，少了一个图标。可以提供一个最小复现环境吗 https://stackblitz.com/

**Comment by abcdbdocker** [comment]
编辑器 是可以支持vue2的吧？

**Comment by abcdbdocker** [comment]
![图片](https://user-images.githubusercontent.com/96030465/153818277-e5f4d548-e6c6-4133-9688-14390e074c85.png)
`<template>
<div>
    <Editor    :plugins="plugins" @change="handleChange" />
</div>
    
</template>

<script>
import { Editor, Viewer } from '@bytemd/vue'
import gfm from '@bytemd/plugin-gfm'
import 'bytemd/dist/index.min.css'

// import importImage from "@bytemd/plugin-import-image"

const plugins = [
  gfm(),
  // importImage(),
  // Add more plugins here
]

export default {
  components: { Editor, Viewer },
  data() {
    return { 
        value: '', 
        plugins, 
        zhHans,
        ruleForm:{},
        rules:{},
        editorConfig:{
          theme:themes.juejin,
          highlight: themes.juejin,
        },

        
        }
  },
  methods: {
    handleChange(v) {
      this.value = v
    },
  },
}
</script>



<style  lang="scss" scoped>
::v-deep .bytemd {
  height: 1000px
}

.box{
    // border: 1px solid red;
    width: 100%;
    height: 65px;
}

::v-deep .el-input__inner{
    height: 63px;
    border: 0px ;
    width: 100%;
    font-size: 40px;
}

::v-deep .el-form-item__content{
  margin-left: 0px !important ; 
}

.text{
  margin: 10px;
  height: 40px;
}
</style>`

我最小化导入 这是我的代码，结果还是没有上传图片的按钮, @vue/cli 4.5.13  npm@6.14.12  @bytemd/vue@1.10.13

**Comment by shengrongchun** [comment]
加上uploadImages 属性就好了
