### ISSUE TITLE
 bytemd version upgrade caused the bug

### ISSUE THREAD

**Issue by xgqfrms** [pd4d10/hashmd#156]
#  bytemd version upgrade caused the bug

> error ❌

https://juejin-markdown-themes.netlify.app/

![image](https://user-images.githubusercontent.com/7291672/159547558-1c30119a-3920-4982-944a-369975dbac95.png)

## solution ✅

> change to the old version

```diff
+ <script src="https://unpkg.com/bytemd@1.10.13/dist/index.min.js"></script>
- <script src="https://unpkg.com/bytemd@1.11.0/dist/index.min.js"></script>
```

## demo

https://cdn.xgqfrms.xyz/theme/index.html

**Comment by pd4d10** [comment]
Thanks for the feedback!

It should have been fixed with the latest version, and the site looks working as expected again.
