### ISSUE TITLE
vite打包后 React的Viewer无法回显出内容

### ISSUE THREAD

**Issue by zk0816** [pd4d10/hashmd#158]
在vite打包后Editor 能正常回显 Viewer不能回显出内容

**Comment by pd4d10** [comment]
可以给一个可复现的 repo 或 https://stackblitz.com/

**Comment by zk0816** [comment]
就是vite 下使用了React  在本地引入你们的组件 不管是editor还是viewer都能正常显示，在vite环境下打包后  editor可以正常使用，viewer没有正常回显 
<img width="907" alt="lQLPDhtFh0Q-F3HNAk7NBxawF33bF5nFbxoCQpantgAlAA_1814_590" src="https://user-images.githubusercontent.com/58846799/160219746-2ff0ff96-99f5-4d12-b87f-77338adaefed.png">
<img width="2249" alt="lQLPDhtFh0Q-F-_NA-7NEZKwSFAB9TM8rwoCQpantgACAA_4498_1006" src="https://user-images.githubusercontent.com/58846799/160219749-bda116f5-b06d-424c-b8d6-c1390594056c.png">
<img width="2436" alt="lQLPDhtFh0Q-GZPNBg7NEwiwMIZindtI4EcCQpanugAlAA_4872_1550" src="https://user-images.githubusercontent.com/58846799/160219760-0ac284d8-c87a-4129-8c4d-19793acc5eb4.png">

**Comment by zk0816** [comment]
就是一个基本的vite打包配置    build: {
        target: 'modules', // 设置最终构建的浏览器兼容目标。modules:支持原生 ES 模块的浏览器
        outDir: 'dist', // 指定输出路径
        assetsDir: 'assets', // 指定生成静态资源的存放路径
        sourcemap: false, // 构建后是否生成 source map 文件
        minify: 'terser' // 混淆器，terser构建后文件体积更小
    },

**Comment by zk0816** [comment]
我的个人项目 blog-weg可以看下

**Comment by pd4d10** [comment]
根据代码来看，`data.content` 更新后 `Viewer` 应该也会更新的。另外也可以试下最新的版本。

**Comment by codingcn** [comment]
我vite+nuxtjs3，也是viewer不会显示，editor能显示。

而且当setup()中存在await fetch()时，editor和viewer都不会显示。
