### ISSUE TITLE
highlight plugin doesn't work

### ISSUE THREAD

**Issue by evan976** [pd4d10/hashmd#160]
Is there any change in the use of the new version of highlight? I imported the highlight style file, but it doesn't work

**Comment by pd4d10** [comment]
Could you please provide a minimal reproduction repo?

**Comment by evan976** [comment]
<img width="678" alt="截屏2022-03-29 下午1 23 45" src="https://user-images.githubusercontent.com/63779056/160539320-f213c539-2d2f-4da2-88b1-77bc068b9df0.png">

<img width="1279" alt="截屏2022-03-29 下午1 10 21" src="https://user-images.githubusercontent.com/63779056/160539404-5845a2cb-0c24-4b85-ae8d-964539b4c6ae.png">

Is it the way I use it?

**Comment by pd4d10** [comment]
It works fine on my local machine.

> Could you please provide a minimal reproduction repo?

**Comment by evan976** [comment]
OK, I'll look into it then, thank you very much for your reply.

**Comment by 1712048533** [comment]
> 

hi friend, Do you have solved this problem,I have the same

**Comment by 1712048533** [comment]
> OK, I'll look into it then, thank you very much for your reply.

my evn is vue

**Comment by pd4d10** [comment]
https://github.com/bytedance/bytemd/issues/167#issuecomment-1090300761
