### ISSUE TITLE
table don't work

### ISSUE THREAD

**Issue by goodforever** [pd4d10/hashmd#161]
Table don't work in example/svelte

**Comment by pd4d10** [comment]
It works, but there does seem to be some issues with the style

**Comment by goodforever** [comment]
Click Table icon ,Insert in left , show in  right

<img width="1228" alt="截屏2022-03-29 20 33 03" src="https://user-images.githubusercontent.com/6078053/160612860-7ffd7dad-0638-42bc-9325-c5baba729b98.png">

**Comment by pd4d10** [comment]
See https://github.com/bytedance/bytemd#viewer-1
