### ISSUE TITLE
Bytemd 1.12.4 svelte does not seem to work

### ISSUE THREAD

**Issue by quasarchimaere** [pd4d10/hashmd#162]
Somehow adding the Editor (see component code below) does not work, and breaks any page with the editor included:

```
<script>
  import { Editor } from "bytemd";
  import gfm from "@bytemd/plugin-gfm";
  import bytemdLocaleDe from "bytemd/lib/locales/de.json";
  import bytemdLocaleEn from "bytemd/lib/locales/en.json";
  import { get } from "svelte/store";
  import { stores } from "@sapper/app";
  const { session } = stores();

  const plugins = [gfm()];

  function handleChange(e) {
    content = e.detail.value;
  }

  function changeLocale(locale) {
    if (locale === "de") {
      return bytemdLocaleDe;
    }
    return bytemdLocaleEn;
  }

  $: currentLocale = changeLocale(get(session).locale);

  export let content;

  let tempContent;

  function initContent() {
    if (content && content !== tempContent) {
      tempContent = content;
    }
  }

  $: initContent(content);
</script>

<div class="mb-3">
  <Editor
    value={tempContent}
    plugins={plugins}
    on:change={handleChange}
    locale={currentLocale}
  />
</div>
```
This error is shown in the console output
```
TypeError: Cannot read properties of undefined (reading '$$')
    at init$1 (index.esm.js:258:46)
    at new Editor (index.esm.js:35629:5)
    at create_fragment (index.esm.js:4897:1)
```
we use:
- svelte 3.46.4
- sapper 0.29.3
- rollup 2.70.1

**Comment by pd4d10** [comment]
Thanks for the feedback!

There doesn't seem to be enough information in this error message. Could you please provide a minimal production repo?

And You may want to refer to the Svelte example [here](https://github.com/bytedance/bytemd/tree/main/examples/svelte)

**Comment by IoannisLafiotis** [comment]
I am having the same issue with the library. When I try to load it into the page it crashes
![Bildschirmfoto 2022-05-30 um 15 04 29](https://user-images.githubusercontent.com/46591718/170998461-63d4bc71-ba64-4b75-abcc-23b57fa2916d.png)
.


I am not sure if it is caused due to incompatibilty with svelte version or node for example.

    "svelte": "^3.47.0",
    "webpack": "^5.48.0",

     node 16.11.1

**Comment by pd4d10** [comment]
Which version are you using? And it would help to troubleshoot if you can provide a reproduction.

**Comment by eslym** [comment]
this issue still exists until version 1.17.1, seems like the issue is with the precompiled svelte code

**Comment by yonnic** [comment]
i have the same issue with the latest svelte,  bytemd 1.17.2 and vite as bundler :(

**Comment by GuoJikun** [comment]
script src="https://unpkg.com/bytemd"   is not work

**Comment by vujovicigor** [comment]
Solution for me was to import it directly from node_modules:
```
    //import { Editor } from 'bytemd';
    import Editor from '../node_modules/bytemd/svelte/editor.svelte';
```

**Comment by OscarLundberg** [comment]
Same issue here
@vujovicigor `s workaround worked for me

**Comment by dbradleyfl** [comment]
@vujovicigor thanks for the workaround. Same issue for me.

**Comment by powellnorma** [comment]
@pd4d10 
I made a repository with which the problem is reproducible: https://github.com/powellnorma/bytemd-problem
It would be great if you could take a look! Thank you.

**Comment by pd4d10** [comment]
It seems related to https://github.com/sveltejs/rollup-plugin-svelte/issues/181

**Comment by tjands** [comment]
That work around is great @vujovicigor. Thanks
