### ISSUE TITLE
代码块在微信公众号中不能正确显示

### ISSUE THREAD

**Issue by ghost** [pd4d10/hashmd#164]
渲染后文章中的代码块，在微信公众号的文章中不能正确显示了，之前没这个问题。请问最近是有更新吗？

**Comment by ghost** [comment]
如果在 https://juejin-markdown-themes.netlify.app/ 使用 github 主题，则没有问题。主要是想了解哪里的问题。辛苦大佬。

**Comment by pd4d10** [comment]
可以提供下复现的 repo

**Comment by ghost** [comment]
> 可以提供下复现的 repo

随便一个代码块应该都能看出来问题。大概是下面这个效果，右侧的渲染框内显示没有问题，但是将内容复制到微信公众号后台时，就能看到区别了。

![image](https://user-images.githubusercontent.com/39549827/160860812-738f0ea4-e6f1-4dc8-8d2a-6db0f37bc5b5.png)

```powershell
https://bytemd.netlify.app/
```

**Comment by pd4d10** [comment]
可以看一下 Editor 右侧的预览有没有高亮效果，如果没有是 bug。如果有而粘贴到外部平台不正常，看起来是外部平台自己识别的问题，可以咨询一下对应的平台

**Comment by ghost** [comment]
> 可以看一下 Editor 右侧的预览有没有高亮效果，如果没有是 bug。如果有而粘贴到外部平台不正常，看起来是外部平台自己识别的问题，可以咨询一下对应的平台

1. 右侧有高亮的效果。
2. 但是半个月之前，即使是复制到外部平台，也是没问题的。
3. 上图中的左侧下半部分，用的也是咱们的组件吧，他那边渲染后的内容，复制到外部平台，也是没问题的。

所以我想问下，最近是有啥更新吗？导致代码块的渲染变了。。

**Comment by pd4d10** [comment]
根据描述来看，可能是复制的 HTML 有细微的差别。可以看下 highlight.js 的升级日志，目前用的是最新版本

**Comment by ghost** [comment]
> 根据描述来看，可能是复制的 HTML 有细微的差别。可以看下 highlight.js 的升级日志，目前用的是最新版本

收到，感谢

**Comment by gh-zhangpeng** [comment]
这个问题，我换了一个主题就可以了。
将 `github-markdown-css` 换成 `juejin-markdown-themes/dist/github.css` 就可以了。但是还是不知道原因。
