### ISSUE TITLE
数学公式重复渲染

### ISSUE THREAD

**Issue by 1712048533** [pd4d10/hashmd#165]
![67a300e765aada17a5b4cf51253a4e7](https://user-images.githubusercontent.com/64450227/160821771-c34d20e2-1133-4826-be92-fb5c85699b3a.png)

以下是代码
import math from "@bytemd/plugin-math";
...
const plugins = [gfm(), gemoji(), mediumZoom(),math(),mermaid()];

本人开发环境是vue

**Comment by pd4d10** [comment]
可以提供下复现的 repo

**Comment by 1712048533** [comment]
> 可以提供下复现的 repo

import gfm from "@bytemd/plugin-gfm";
import gemoji from "@bytemd/plugin-gemoji";
import highlight from "@bytemd/plugin-highlight-ssr";
import mediumZoom from "@bytemd/plugin-medium-zoom";
import math from "@bytemd/plugin-math";
import mermaid from '@bytemd/plugin-mermaid'
import UserPopover from '../../components/UserPopover/UserPopover.vue'
const zhHans = {
    "bold": "粗体",
    "boldText": "粗体文本",
    "cheatsheet": "Markdown 语法",
    "closeHelp": "关闭帮助",
    "closeToc": "关闭目录",
    "code": "代码",
    "codeBlock": "代码块",
    "codeLang": "编程语言",
    "codeText": "代码",
    "exitFullscreen": "退出全屏",
    "exitPreviewOnly": "恢复默认",
    "exitWriteOnly": "恢复默认",
    "fullscreen": "全屏",
    "h1": "一级标题",
    "h2": "二级标题",
    "h3": "三级标题",
    "h4": "四级标题",
    "h5": "五级标题",
    "h6": "六级标题",
    "headingText": "标题",
    "help": "帮助",
    "hr": "分割线",
    "image": "图片",
    "imageAlt": "alt",
    "imageTitle": "图片描述",
    "italic": "斜体",
    "italicText": "斜体文本",
    "limited": "已达最大字符数限制",
    "lines": "行数",
    "link": "链接",
    "linkText": "链接描述",
    "ol": "有序列表",
    "olItem": "项目",
    "preview": "预览",
    "previewOnly": "仅预览区",
    "quote": "引用",
    "quotedText": "引用文本",
    "shortcuts": "快捷键",
    "source": "源代码",
    "sync": "同步滚动",
    "toc": "目录",
    "top": "回到顶部",
    "ul": "无序列表",
    "ulItem": "项目",
    "words": "字数",
    "write": "编辑",
    "writeOnly": "仅编辑区",
    "strikethrough":"删除线",
    "task list":"任务队列",
    "tasklist":"任务队列",
    "inline formula":""
  }
const plugins = [gfm(), gemoji(),highlight(true), mediumZoom(),math(),mermaid()];

export default{
    name:'Blog',
    data(){
        return{
            value:"$2^x$"
        }
    },
    methods: {
        handleChange(e){
            console.log(e)
            this.value = e;
        }
    },
    components:{
        UserPopover
    }
}



<Viewer v-model="value" :plugins="plugins">
</Viewer>

**Comment by 1712048533** [comment]
`<Viewer v-model="value" :plugins="plugins">

        </Viewer>`

**Comment by 1712048533** [comment]
> <Viewer v-model="value" :plugins="plugins"></Viewer>

**Comment by 1712048533** [comment]
![image](https://user-images.githubusercontent.com/64450227/160839233-40989bab-c8a3-41f2-a1cf-453d2f19ef61.png)

**Comment by xuxin666666** [comment]
样式问题，你写入公式后，有这两个元素：`div.katex-mathml`和`div.katex-html`，不引入`katex`的样式的话，第一个是公式，第二个是重复的值；引入的话，第一个相当于被隐藏，然后第二个成了公式了
