### ISSUE TITLE
@bytemd/plugin-highlight-ssr插件无法高亮代码

### ISSUE THREAD

**Issue by ace0109** [pd4d10/hashmd#167]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/18433582/161515041-6b756c68-d607-4f47-a12b-6c561a344e72.png">
<img width="713" alt="image" src="https://user-images.githubusercontent.com/18433582/161515093-a649071f-75fb-466f-b872-1d393902ba15.png">
使用ssr版的highlight插件，渲染出来的代码块无高亮。

**Comment by pd4d10** [comment]
Looks similar to #160 . Could you please provide a minimal reproduction repo?

**Comment by ace0109** [comment]
@pd4d10 
https://codesandbox.io/s/quizzical-goldstine-wz7zc4?file=/pages/index.js

**Comment by pd4d10** [comment]
感谢提供复现的工程。看起来好像是构建的问题，我跟进一下

**Comment by pd4d10** [comment]
已临时修复，可以试一下 v1.13.1 版本

**Comment by evan976** [comment]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/63779056/162251197-13a2536f-a1ac-4d84-a9f2-66e6962c1bb9.png">
ok, it works fine now, thanks a lot

**Comment by pd4d10** [comment]
Thanks for the feedback. Closing, feel free to reopen it if there is something wrong.
