### ISSUE TITLE
能不能把文档写下

### ISSUE THREAD

**Issue by ideaviewes** [pd4d10/hashmd#168]
现在的文档太简略了，example中的例子也是
开发起来完全是靠猜的，或者没时间的话把
https://bytemd.js.org/playground/
代码也开源下也行

**Comment by pd4d10** [comment]
文档可以参照 README。Playground 代码：

https://github.com/bytedance/bytemd/tree/main/packages/playground

**Comment by ideaviewes** [comment]
好的，谢谢
