### ISSUE TITLE
代码高亮这部分有什么可以配置的吗？

### ISSUE THREAD

**Issue by ideaviewes** [pd4d10/hashmd#169]
@bytemd/plugin-highlight-ssr，比如复制代码，和显示行号~

**Comment by pd4d10** [comment]
提到的这个插件的选项与 https://github.com/rehypejs/rehype-highlight 是保持一致的，可以看下是否支持

**Comment by ideaviewes** [comment]
看了不行，如果能实现这样的功能就好了
