### ISSUE TITLE
编辑器的onChange事件里，获取不到最新的state

### ISSUE THREAD

**Issue by ace0109** [pd4d10/hashmd#171]
https://codesandbox.io/s/quizzical-goldstine-wz7zc4?file=/pages/index.js

上面这个是例子，编辑器的onChange事件，拿不到最新的state

**Comment by pd4d10** [comment]
看起来 React useState 的行为就是如此。可以试试把 state 换成 primitive value，比如

```js
const [title, setTitle] = useState('')
const [content, setContent] = useState('')
```

**Comment by ace0109** [comment]
@pd4d10 不是的吧，写了很久的react了，没遇到过。比如上面的input的onChange，就不会出现这个问题。

**Comment by ace0109** [comment]
这甚至导致了，我想在编辑器的onChange事件里去触发自动保存草稿的功能，这时候获取到的state都是初始值
即使我把state这样分开
```js
const [title, setTitle] = useState('')
const [content, setContent] = useState('')
```
在编辑器的onChange事件触发后去做某些事情，获取到的title也是空字符串

**Comment by pd4d10** [comment]
可以参考下这个示例：https://github.com/bytedance/bytemd/tree/main/examples/react

**Comment by ace0109** [comment]
@pd4d10 我在写个例子给你看一下哈
[https://codesandbox.io/s/hardcore-wind-5begev?file=/src/App.js](https://codesandbox.io/s/hardcore-wind-5begev?file=/src/App.js)

![image](https://user-images.githubusercontent.com/18433582/163325938-24aaaec5-cda7-47d3-8fb7-7eb6359256c6.png)

复现步骤：
1、title的初始值是123
2、修改title输入框的值
3、输入编辑器的值，触发onChange事件，打印出来的title，还是123

**Comment by ace0109** [comment]
@pd4d10 
我通过调试源码，发现可能是监听onChange事件，不应该放在useEffect里。我把onChange加入到useEffect的依赖里，可以解决这个问题，但是会重复造成编辑器初始化，应该在做个判断，是否已经初始化了编辑器，或者监听onChange应该在别的地方使用。

**Comment by ace0109** [comment]
我提个PR
