### ISSUE TITLE
Vue 3下Viewer组件使用hightlight、math、mermaid插件后在销毁组件时会报错

### ISSUE THREAD

**Issue by coder-zhc** [pd4d10/hashmd#173]

**Comment by coder-zhc** [comment]
https://codesandbox.io/s/affectionate-antonelli-qyc9zi?file=/src/App.vue
插件不会生效，并且在销毁或页面切换的时候会报错

**Comment by pd4d10** [comment]
cc the authors @lankeo @heiyehk, do you encounter this issue?

Commit: https://github.com/bytedance/bytemd/commit/b14a4f1ce6e16210965cf604ff8b70b0cc078368

**Comment by link1412** [comment]
> https://codesandbox.io/s/affectionate-antonelli-qyc9zi?file=/src/App.vue 插件不会生效，并且在销毁或页面切换的时候会报错

我也遇到了这个问题，medium-zoom插件页面切换时也会报这个错

**Comment by heiyehk** [comment]
@coder-zhc @pd4d10 @wangyan666 I'm so sorry I just saw this message now. I am now trying to reproduce and solve this problem.

**Comment by pd4d10** [comment]
Changes in #186 have been released as v1.15.0
