### ISSUE TITLE
参考#126 (comment)生成目录无效   (imported as 'ByteMd') was not found in '@bytemd/vue'

### ISSUE THREAD

**Issue by sanvae** [pd4d10/hashmd#176]
参考了#126 (comment) 提示"export 'default' (imported as 'ByteMd') was not found in '@bytemd/vue'
版本为"@bytemd/vue": "^1.13.1",是否是版本问题？
```
<template>
    <ByteMd ref="editor" :value="value" :locale="zhHans" :plugins="plugins" :editorConfig="editorConfig" @change="handleChange" />
</template>
<script>
import ByteMd from '@bytemd/vue'
import zhHans from 'bytemd/locales/zh_Hans.json'

const plugins = [
]

const editorConfig = {
    lineNumbers: true
}

export default {
    components: { ByteMd },
    data() {
        return { 
            value: '', 
            plugins, 
            editorConfig,
            zhHans
        }
    },
    methods: {
        handleChange(v) {
            this.value = v;
        }
    }
}
</script>
```

**Comment by Slash214** [comment]
> 参考了#126 (comment) 提示"export 'default' (imported as 'ByteMd') was not found in '@bytemd/vue' 版本为"@bytemd/vue": "^1.13.1",是否是版本问题？
> 
> ```
> <template>
>     <ByteMd ref="editor" :value="value" :locale="zhHans" :plugins="plugins" :editorConfig="editorConfig" @change="handleChange" />
> </template>
> <script>
> import ByteMd from '@bytemd/vue'
> import zhHans from 'bytemd/locales/zh_Hans.json'
> 
> const plugins = [
> ]
> 
> const editorConfig = {
>     lineNumbers: true
> }
> 
> export default {
>     components: { ByteMd },
>     data() {
>         return { 
>             value: '', 
>             plugins, 
>             editorConfig,
>             zhHans
>         }
>     },
>     methods: {
>         handleChange(v) {
>             this.value = v;
>         }
>     }
> }
> </script>
> ```

那是别人实现react方法的代码，vue需要自己实现。@bytemd/vue目前1.13.1支持导出的是viewer和editor组件，可以去代码里面查看只导出这两种，所以你应该使用viewer组件去展示，同时目录方法，需要你自行去编辑代码实现。博主问题提供的是一个方法，通过渲染的标签或者md文档的# 可以判断存在一级标题二级标题类似，再在侧边栏生成。
