### ISSUE TITLE
SyntaxError: Unexpected token export when trying to build SvelteKit

### ISSUE THREAD

**Issue by M4TY** [pd4d10/hashmd#180]
I have ran into this error when trying to build my SvelteKit app:

`export { mathSsr as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:196:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Promise.all (index 1)
[SyntaxError: Unexpected token 'export']
`

When I remove mathSsr the same error appears in gfm and other plugins. Is there any way to fix this? I am using the newest SvelteKit version.

**Comment by pd4d10** [comment]
There is an example built with Sveltekit here: https://github.com/bytedance/bytemd/tree/main/examples/svelte

Could you please provide a minimal reproduction?

**Comment by M4TY** [comment]
I have followed the example before, but note that when trying to build the example you get the same error. What I believe could be the fix is adding **type: "module"** to every package.json file of every plugin. At least that fixed the problem with SvelteKit. Do you think I could make a pull request? Or could this addition break something else.

**Comment by pd4d10** [comment]
It seems to work correctly on my local machine. what's the difference between your project and the example?

**Comment by M4TY** [comment]
None. The problem is though that even the example doesn't work on my machine, do you mind checking what version of kit are you using?

**Comment by pd4d10** [comment]
After some investigation, I reproduced this issue while running the `build` process.

I guess it's more like a SvelteKit issue. We already provide both the CJS and ESM bundle with correct [conditional-exports](https://nodejs.org/api/packages.html#conditional-exports), while SvelteKit seems not to load the correct one.

**Comment by M4TY** [comment]
I apologize if I did not mention that. Yes, I get this error when running **npm run build**. Thank you for your response.

**Comment by pd4d10** [comment]
cc @benmccann may have more context on this issue

**Comment by benmccann** [comment]
The issue is in the `@bytemd/plugin-gfm` package. Node.js requires that ESM files either live in a package with `"type": "module"` or that they have an `.mjs` file ending. However, the package does not have `"type": "module"` and uses an `.esm.js` file ending. The error is coming directly from Node.js and can only be fixed in the `@bytemd/plugin-gfm` package.

**Comment by pd4d10** [comment]
It should be treated as a CJS package in SSR scenarios.

Does Sveltekit only support ESM packages?

**Comment by benmccann** [comment]
I believe that Vite (which powers SvelteKit) does run it as a CJS package but does an `import` of dependencies and the `package.json` for `@bytemd/plugin-gfm` states that imports should use `./dist/index.esm.js`. But in the very near future Vite will switch to building all packages as ESM rather than CJS for SSR. It would definitely be a good idea to make the ESM builds work on Node.js by renaming the file extension from `.esm.js` to `.mjs`

**Comment by pd4d10** [comment]
Oh, I think I get your point. I guess the current best solution is to rename `.esm.js` to `.mjs`

As for `type: module`, I'm very glad to move to ESM at the next major version. The reason to stay CJS is for backward compatibility.

**Comment by pd4d10** [comment]
Hi @M4TY , could you please update your PR to rename `.esm.js` to `.mjs` instead of adding `type: module`?

Then we will not break the other SSR frameworks such as Next.js or Nuxt.js

**Comment by M4TY** [comment]
Yes, I am gonna do it right away.

**Comment by M4TY** [comment]
Update the PR. Thanks for your cooperation @benmccann & @pd4d10!

**Comment by pd4d10** [comment]
Published v1.14.0
