### ISSUE TITLE
Enable full "Markdown" behavior

### ISSUE THREAD

**Issue by filipedeschamps** [pd4d10/hashmd#183]
I noticed that ByteMD somehow does not fully use the [Markdown mode](https://codemirror.net/mode/markdown/) from CodeMirror.

## ByteMD behavior

https://user-images.githubusercontent.com/4248081/167883020-2d4223f0-a8a6-44fc-9f1c-1375d3a59feb.mov

## CodeMirror behavior

https://user-images.githubusercontent.com/4248081/167883366-18e18ca0-898c-4335-9456-ab770564c932.mov

This could be the default, but in the meantime, is there any extra config to enable this?

**Comment by pd4d10** [comment]
Actually, it's not a built-in feature in Markdown mode. It's an addon named continue list.

But we can add it because it's indeed handy for writers. Will be released in the next version soon.

**Comment by pd4d10** [comment]
v1.15.0 released
