### ISSUE TITLE
Unble to use bytemd with svelte sapper

### ISSUE THREAD

**Issue by saikumar305** [pd4d10/hashmd#187]
Hey , I am new to svelte,
found this beautiful rich text editor but I am unable to use it in my app.
`[rollup-plugin-svelte] The following packages did not export their package.json file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file - bytemd`

And i have installed bytemd as a dev dependency

**Comment by dkotik** [comment]
I have just experienced the same issue. The installation instructions are unclear.

**Comment by pd4d10** [comment]
Could you please provide a minimal reproduction?

If you are using SvelteKit, there is also an example [here](https://github.com/bytedance/bytemd/tree/main/examples/svelte)

**Comment by saikumar305** [comment]
> Could you please provide a minimal reproduction?
> 
> If you are using SvelteKit, there is also an example [here](https://github.com/bytedance/bytemd/tree/main/examples/svelte)

I am using Svelte sapper , because its my requirement , I have followed the docs and added minimal code to display the editor, still I am  getting the below error.

![bytemd-fail](https://user-images.githubusercontent.com/60888829/169560584-57fbdf24-e8ec-4f84-aad7-2208e7aea13e.png)

**Comment by pd4d10** [comment]
Sapper seems to be discontinued. From https://sapper.svelte.dev/docs

> Sapper's succesor, [SvelteKit](https://kit.svelte.dev/), is currently available for use. All development efforts moving forward will be focused on [SvelteKit](https://kit.svelte.dev/).

**Comment by CPunisher** [comment]
It is recommended to migrate your project to [SvelteKit](https://kit.svelte.dev/docs/migrating).
But if there is some reason, you can take the following steps according to [svelterjs/sapper#774](https://github.com/sveltejs/sapper/issues/774): 

1. Installed `bytemd` as a dev dependency.
2. Import `Editor` with 
```js
import { Editor } from 'bytemd/dist/svelte-entry';

// or 
import Editor from 'bytemd/dist/editor.svelte';
```
3. When you run the development server, you will get an error about missing `@rollup/plugin-json`. So you should install it as dev dependency, and configure it in `rollup.config.js` (both client and server).
```js
import json from '@rollup/plugin-json';

export default {
  client: {
    plugins: [
      // ...
      json(),
    ]
  },
  server: {
    plugins: [
      // ...
      json(),
    ]
  }
}
```

But I'm not sure there are not other bugs.
