### ISSUE TITLE
examples/svelte-rollup/package.json does not depend on bytemd?

### ISSUE THREAD

**Issue by koo5** [pd4d10/hashmd#19]
and even if i `npm i bytemd` in the directory, i still get ` Uncaught ReferenceError: bytemd is not defined` in browser console.

**Comment by pd4d10** [comment]
Oh, these packages are actually missing. Because in the development case these packages are resolved in the root `node_modules`.

Run `yarn && yarn dev` at the root directory should solve this issue.

**Comment by pd4d10** [comment]
In your own project, these packages should be installed manually if used.

**Comment by pd4d10** [comment]
We use pnpm in the latest main branch and include examples in the monorepo workspace.

So this should have been fixed.
