### ISSUE TITLE
粘贴事件如何获取当前输入框的焦点

### ISSUE THREAD

**Issue by sanvae** [pd4d10/hashmd#191]
RT

**Comment by wmy94827** [comment]
同问~ 怎么实现粘贴 保留样式。插入指定位置 
setSelection我看到没有暴露此方法

**Comment by pd4d10** [comment]
可以参考 https://github.com/bytedance/bytemd/pull/192#issuecomment-1140437569

可以在 `editorEffect` 钩子中获取到 codemirror 的实例
