### ISSUE TITLE
默认菜单怎么没有图片选项菜单？怎么开启？

### ISSUE THREAD

**Issue by jaychou2012** [pd4d10/hashmd#195]
默认菜单怎么没有图片选项菜单？怎么开启？

**Comment by Glowin** [comment]
markdown 只支持插入图片链接，原生不支持图片上传。
你可以写一个上传图片的插件，贡献代码。

**Comment by pd4d10** [comment]
The `uploadImages` option is probably you need, see this section: https://github.com/bytedance/bytemd#editor
