### ISSUE TITLE
如何自定义菜单，加入我想要的按钮自定义功能

### ISSUE THREAD

**Issue by jaychou2012** [pd4d10/hashmd#196]
如何自定义菜单，加入我想要的按钮自定义功能

**Comment by 739528570** [comment]
+1

**Comment by snail-boy** [comment]
不支持html

**Comment by cxyguopong** [comment]
sdf**asd asdf s**df  sdafsd fsdfa sdaf
ds
fasd
f
sd afsdfs_da fsd_af
![Uploading 有问题点我！安装教程！.png…]()
