### ISSUE TITLE
如何导出html和markdown代码？

### ISSUE THREAD

**Issue by jaychou2012** [pd4d10/hashmd#197]
如何导出html和markdown代码？

**Comment by heiyehk** [comment]
你说的导出是指文件还是console输出？
You said that the export is refers to the file or the console output?

**Comment by heiyehk** [comment]
> 如何导出html和markdown代码？

你说的导出是指文件还是console输出？
You said that the export is refers to the file or the console output?

**Comment by jaychou2012** [comment]
console输出




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月20日(星期一) 下午3:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bytedance/bytemd] 如何导出html和markdown代码？ (Issue #197)





  
如何导出html和markdown代码？
  
你说的导出是指文件还是console输出？
 You said that the export is refers to the file or the console output?
 
&mdash;

**Comment by heiyehk** [comment]
> console输出
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年6月20日(星期一) 下午3:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [bytedance/bytemd] 如何导出html和markdown代码？ (Issue #197) 如何导出html和markdown代码？ 你说的导出是指文件还是console输出？ You said that the export is refers to the file or the console output? &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

[https://bytemd.netlify.app/#usage](https://bytemd.netlify.app/#usage)

这里有具体的使用教程

**Comment by codingcn** [comment]
@heiyehk 需要类似这样的api，https://nhn.github.io/tui.editor/latest/ToastUIEditorCore#getHTML

简单的使用场景，直接存储渲染后的html到db，这样就可以做页面缓存。不需要每次显示文章内容都走viewer降低页面渲染速度

**Comment by pd4d10** [comment]
这里可能需要注意一点，部分情况下 HTML 中并不包括全量的内容信息。比如 plugin 中使用了 `viewerEffect` hook 的情况下，有一部分效果是在浏览器中执行 JS 代码动态生成的，最终渲染效果可能会由于环境的不同而有差异

**Comment by dvlin-dev** [comment]
请问有 getHtml 的 Api 吗

**Comment by jaychou2012** [comment]
E-MAIL 已收到。
