### ISSUE TITLE
Where can I find the source code of https://bytedance.github.io/bytemd/?

### ISSUE THREAD

**Issue by ghost** [pd4d10/hashmd#20]
Where can I find the source code of https://bytedance.github.io/bytemd/?

**Comment by pd4d10** [comment]
See https://github.com/bytedance/bytemd/tree/main/examples/svelte

It is built with Webpack. There is also [another example](https://github.com/bytedance/bytemd/tree/main/examples/svelte-rollup) built with Rollup

**Comment by ghost** [comment]
ok ,thx
