### ISSUE TITLE
数学求和公式 可视化问题

### ISSUE THREAD

**Issue by gfhe** [pd4d10/hashmd#202]
在使用[https://bytemd.js.org/playground/](`https://bytemd.js.org/playground/`) 时，发现如下问题（截图）：

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/90042648/174943664-ed32a497-bc5a-45c4-bf50-8c994e6820a5.png">

在上图中，数学表达式显示错误。正确的Latex公式解析应该显示为（github解析markdown生成的）:

$$R\_N(h) = \frac{1}{N} \sum\_{i=1}^N l(x\_i, y\_i))$$

**Comment by pd4d10** [comment]
Math plugin 使用的是 https://katex.org/ ，可能与 MathJax 的渲染逻辑有一些区别

**Comment by lesonky** [comment]
先引入 css，然后插件配置一下
```ts
import mathLocal from '@bytemd/plugin-math/locales/zh_Hans.json'; // 中文包
import 'katex/dist/katex.css'; // 样式

const plugins = [
  math({
    locale: mathLocal,
    katexOptions: { output: 'html' }, // https://github.com/KaTeX/KaTeX/issues/2796
  }),
 ...otherPlugins
];
```

**Comment by carveybunt** [comment]
> 

大佬，katexOptions 是怎么导入的呢？能分享下代码吗？

**Comment by carveybunt** [comment]
> 先引入 css，然后插件配置一下
> 
> ```ts
> import mathLocal from '@bytemd/plugin-math/locales/zh_Hans.json'; // 中文包
> import 'katex/dist/katex.css'; // 样式
> 
> const plugins = [
>   math({
>     locale: mathLocal,
>     katexOptions: { output: 'html' }, // https://github.com/KaTeX/KaTeX/issues/2796
>   }),
>  ...otherPlugins
> ];
> ```

@lesonky  大佬，katexOptions 是怎么导入的呢？能分享下代码吗？
