### ISSUE TITLE
SSR error using bytemd/vue with nuxt2

### ISSUE THREAD

**Issue by yang-zhongtian** [pd4d10/hashmd#206]
When I use the vue component in nuxt, I got `document is not defined`, which might be caused by the server side. I've found a issue(#159) that is fixed mentioned about this, but after I updated bytemd the error is still there. Wish for someone's help!

**Comment by yang-zhongtian** [comment]
This is the error page:
![screenshot](https://user-images.githubusercontent.com/23440907/177459853-e6d18df0-18af-4a45-aa74-9fd5a8e32c5b.png)

**Comment by pd4d10** [comment]
Could you please try v1.17.0?

**Comment by yang-zhongtian** [comment]
Thanks, but among the plugins I'm using, the gfm plugin is still not working, is it not SSR compatible? Here's the screenshot.
![screenshot](https://user-images.githubusercontent.com/23440907/177499481-d7a57c94-dd09-4ecb-a978-e7ce330180c3.png)

**Comment by yang-zhongtian** [comment]
Apart from this, everything seems fine :)

**Comment by pd4d10** [comment]
Could you please try v1.17.1? Feel free to reopen it if there are other problems.

**Comment by quasarchimaere** [comment]
@pd4d10 v1.17.1 seems to have fixed this isse, the last working version before was v1.15.0, both 16 and 17 did not work for me (same issue, even though i use sveltekit)
