### ISSUE TITLE
support for codefence code highlight for common languages

### ISSUE THREAD

**Issue by sanvishal** [pd4d10/hashmd#207]
I was trying to figure out why the codefencing does not work on js though I've set `fencedCodeBlockHighlighting: true` in the `editorConfig`, looks like there are only certain languages that support code fence highlighting, **is it possible to add highlighting for any language inside codefence?** or is it possible to modify the `CodeMirror` object to add custom modes?

![image](https://user-images.githubusercontent.com/15110377/177573544-18b8bd8d-1837-44e4-a88d-5fff029eba5d.png)

thanks!

**Comment by pd4d10** [comment]
> is it possible to modify the `CodeMirror` object to add custom modes

Sure, see the example here: https://github.com/bytedance/bytemd/pull/192#issuecomment-1140437569

**Comment by sanvishal** [comment]
thanks, but codemirror only allows to define the **modes** when [creating the codemirror instance](https://github.com/bytedance/bytemd/blob/main/packages/bytemd/src/editor.ts#L23). (I think, I'm not sure)

is it possible to add extra modes after codemirror instance creation?
