### ISSUE TITLE
How to submit a translation using the "translation platform"?

### ISSUE THREAD

**Issue by filipedeschamps** [pd4d10/hashmd#214]
I've used the [translation platform](https://hosted.weblate.org/projects/bytemd/) to fix some long text issues in the `pt_BR` locale:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/4248081/183708643-6a3fb6bd-805f-4935-accd-05f0358fbb6c.png">

But I don't know to submit the changes I've made on that platform. I've already changed the text in there, but I don't know how to do a "final submit".

**[edit]**

Fixing the `Texto do bloco` automatically fixes `Diagrama Merdmaid` below.

**Comment by filipedeschamps** [comment]
Also, I couldn't find a way to fix the `(url "title")` in the `Image` example. It doesn't make sense I guess and it should just be `(url)`, like in the `Link` example.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/4248081/183709455-fa74a5df-5b92-493d-afb4-d3f696aa0bdb.png">

**Comment by pd4d10** [comment]
> fix the `(url "title")` in the `Image` example

The `title` here is used to set `img`'s title

**Comment by pd4d10** [comment]
> how to do a "final submit".

It would automatically send a PR, see https://github.com/bytedance/bytemd/pull/210

**Comment by filipedeschamps** [comment]
> Member

That's neat. Thank you!
