### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ghost** [pd4d10/hashmd#22]
not work right on antd Form.Item,get the `Unhandled Rejection (TypeError): Cannot read property 'split' of undefined` error.

**Comment by pd4d10** [comment]
Could you give a reproductive example, such as a GitHub repo or https://codesandbox.io/

**Comment by ghost** [comment]
https://codesandbox.io/s/amazing-hugle-hmwhk

**Comment by pd4d10** [comment]
It seems caused by `Form.Item`:

https://ant.design/components/form-cn/#API

> 被设置了 name 属性的 Form.Item 包装的控件，表单控件会自动添加 value（或 valuePropName 指定的其他属性） onChange（或 trigger 指定的其他属性），数据同步将被 Form 接管，这会导致以下结果：
>
> 你不再需要也不应该用 onChange 来做数据收集同步（你可以使用 Form 的 onValuesChange），但还是可以继续监听 onChange 事件。
> 
> 你不能用控件的 value 或 defaultValue 等属性来设置表单域的值，默认值可以用 Form 里的 initialValues 来设置。注意 initialValues 不能被 setState 动态更新，你需要用 setFieldsValue 来更新。
> 
> 你不应该用 setState，可以使用 form.setFieldsValue 来动态改变表单值。

**Comment by ghost** [comment]
OK，then can't be used together.

**Comment by pd4d10** [comment]
其实是可以的，有两种方法

1. 去掉 `name`，变成不受控组件
2. 按照文档里说的设置 `initialValues`，不要传 `undefined` 作为 `value` 给 `Editor `

这个错误是因为传了 `undefined` 过来，导致 CodeMirror 内部调用 `split` 方法报错了。
