### ISSUE TITLE
React Vite打包部署后 代码高亮不生效highlight.js/styles/vs.css（本地运行是可以的）

### ISSUE THREAD

**Issue by HuangDaohong** [pd4d10/hashmd#220]
![image](https://user-images.githubusercontent.com/43535242/187818390-eeb70684-16ca-4526-bbb6-aec9f68fecef.png)
![image](https://user-images.githubusercontent.com/43535242/187818457-42fb77f6-080f-442c-b830-37e5964cec56.png)

**Comment by codingcn** [comment]
我是vite+nuxt3，editer本地运行会高亮，编译打包后就不会高亮了，viewer没问题。

**Comment by pd4d10** [comment]
如果是开发环境和生产环境不一致，可以检查一下是否打包工具的问题
