### ISSUE TITLE
Upload file plugin

### ISSUE THREAD

**Issue by shivshankardayal** [pd4d10/hashmd#23]
bytemd needs an upload file plugin.

**Comment by pd4d10** [comment]
Does `@bytemd/plugin-import-image` meet your needs?

**Comment by shivshankardayal** [comment]
No it does not. But I guess I can write a plugin to accept any file type.

**Comment by pd4d10** [comment]
Yeah, it is easy to write your own plugin.

Just curious about what this use case is

**Comment by shivshankardayal** [comment]
Yes I guess I will use image plugin. There are many other ways to do files which are easier.

**Comment by pd4d10** [comment]
As image uploading is a very common feature in practice, we make it built-in in the latest version:

```js
<Editor
  uploadImages={async (files) => {
    // upload images to your server
    return [
      {
        url: '',
        alt: '', // optional
        title: '' // optional
      }
    ]
  })
/>
```

`@bytemd/plugin-import-image` is deprecated.

**Comment by yxb666** [comment]
请问最新版本 @bytemd/vue 1.9.2 有上传图片的功能了吗？ 引入之后没有看到关于 img上传的按钮

**Comment by 0gust1** [comment]
We also need a file upload feature. We'll look into custom plugin (as stated, it's not that different of the image upload plugin).

The use case is enable users to upload a file and generate a link to this file in the document.=
