### ISSUE TITLE
How to display iframe?

### ISSUE THREAD

**Issue by wood3n** [pd4d10/hashmd#233]
I tried to embed codesandbox `iframe` in md, but it doesn't be rendered.
![image](https://user-images.githubusercontent.com/31716713/200839357-82097fb6-f013-47b9-a0ac-9e4b863bb0d4.png)

**Comment by pd4d10** [comment]
You can specify sanitize strategy via the `sanitize` prop.

Notice that `iframe` can lead to XSS attack, and use it carefully if your content can't be trusted (for example, UGC scenario)
