### ISSUE TITLE
Why toolbar icons are no available when it is in tab mode?

### ISSUE THREAD

**Issue by NormandoHall** [pd4d10/hashmd#240]
Switching to tab mode, the toolbar icons are gone in Write tab

**Comment by pd4d10** [comment]
It's by design, because the tab mode is for small screens, on which the tab bar doesn't have enough space to show lots of icons.

You can go to [the playground](https://bytemd.js.org/playground/), and adjust the browser screen size to see the effect.

**Comment by NormandoHall** [comment]
@pd4d10 thanks for the explanation and this great editor!
