### ISSUE TITLE
如何自定义工具栏？

### ISSUE THREAD

**Issue by allinu** [pd4d10/hashmd#241]
### 目前的工具栏状态

![](https://i0.hdslb.com/bfs/album/20a50c6df4474b21daa57e28c8f437d25e28d7f3.png)

### 期望的工具栏状态

![](https://i0.hdslb.com/bfs/album/9a63b77ad840293547e901dd2ed58d1cce75f8eb.png)

**Comment by pd4d10** [comment]
可以参考 https://github.com/bytedance/bytemd#authoring-a-plugin ，action 部分

**Comment by allinu** [comment]
@pd4d10 谢谢🙏，我这这就去实现一下，感谢回答
