### ISSUE TITLE
option.sanitize displays warnings in vue, Can fix this?

### ISSUE THREAD

**Issue by T-miracle** [pd4d10/hashmd#247]
The type of sanitize in vue is `Object`

In the document, the sanitize type is `(schema: Schema) => Schema`

This causes vue to prompt a warning:

```
[Vue warn]: Invalid prop: type check failed for prop "sanitize". Expected Object, got Function  
```

**Comment by T-miracle** [comment]
![Snipaste_2022-12-27_15-16-05](https://user-images.githubusercontent.com/44044121/209627440-46995cd5-48ab-424f-b3e0-bf757524cc62.png)
![Snipaste_2022-12-27_15-16-30](https://user-images.githubusercontent.com/44044121/209627459-7bc5c89a-0391-400e-a0ae-d18371ced61d.png)
![Snipaste_2022-12-27_15-17-12](https://user-images.githubusercontent.com/44044121/209627471-31d41454-c280-4551-b779-def471705092.png)

**Comment by AnzhiZhang** [comment]
same issue in @bytemd/vue, but I am using Editor with `sanitize` attribute
![image](https://user-images.githubusercontent.com/37402126/210154523-0ac27be7-f5ca-4458-9b6a-ced4e294978f.png)

**Comment by pd4d10** [comment]
Thanks for the feedback!

Would you like to take this issue and submit a PR?

**Comment by AnzhiZhang** [comment]
#251

**Comment by T-miracle** [comment]
> #251

Great， I just saw the response, and you already submitted it first，so fast！@pd4d10
