### ISSUE TITLE
Why is the toolbar hidden in `tab` mode?

### ISSUE THREAD

**Issue by codeit-ninja** [pd4d10/hashmd#262]
Is there an option to show the toolbar in tab mode aswell? I dont understand why its hidden in tab mode...

**Comment by dmccallie** [comment]
I have the same need. 
Does anyone have a clue on how to turn on toolbar in tab mode (or better yet, to just have the Editor without any preview option, but with toolbar enabled?)
Thanks!

**Comment by pd4d10** [comment]
Ref: https://github.com/bytedance/bytemd/issues/240#issuecomment-1345150746
