### ISSUE TITLE
how to change katex to Mathjax?

### ISSUE THREAD

**Issue by mqingqing123** [pd4d10/hashmd#273]
如何把 katex换成 mathjax？
请指导一下

**Comment by CPunisher** [comment]
参考 https://github.com/bytedance/bytemd/blob/main/packages/plugin-math/src/index.ts 实现 plugin

利用 [remark-math](https://github.com/remarkjs/remark-math) 在 remark 阶段生成带数学公式内容的 `<div class=".math.math-inline">`  或 `<div class=".math.math-display">` DOM 节点，在 viewerEffect 阶段 query 他们，并利用 mathjax 生成 svg 节点插入到里面
