### ISSUE TITLE
feature: 代码编辑器支持 diff 和代码语言同时使用

### ISSUE THREAD

**Issue by zh-lx** [pd4d10/hashmd#274]
目前当代码编辑器的可选语言为 diff 时，可以增加语言的背景色，但是失去了语言的高亮功能，希望能支持两者同时使用

**Comment by pd4d10** [comment]
这个应该是 highlight.js 的设定，如果有类似需求可以使用满足你需求的第三方库来实现 plugin。

**Comment by zh-lx** [comment]
这个需求辛苦支持一下吧，我在用掘金写文章时感觉还挺常用的



---- 回复的原邮件 ----
| 发件人 | Rongjian ***@***.***> |
| 日期 | 2023年04月19日 12:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [bytedance/bytemd] feature: 代码编辑器支持 diff 和代码语言同时使用 (Issue #274) |

这个应该是 highlight.js 的设定，如果有类似需求可以使用满足你需求的第三方库来实现 plugin。
