### ISSUE TITLE
vue3 常规引入，预览区不展示内容

### ISSUE THREAD

**Issue by kvchen95** [pd4d10/hashmd#277]
vue3 常规引入，预览区不展示内容
![image](https://user-images.githubusercontent.com/38784525/221356517-767c8637-02b1-4dad-a8d4-31b844ae172d.png)

// package.json
```json
"dependencies": {
    "@bytemd/plugin-gfm": "^1.20.2",
    "@bytemd/plugin-highlight": "^1.20.2",
    "@bytemd/plugin-math": "^1.20.2",
    "@bytemd/vue": "^1.20.2",
    "@bytemd/vue-next": "^1.20.2",
    "axios": "^1.3.2",
    "bytemd": "^1.20.2",
    "pinia": "^2.0.28",
    "uid": "^2.0.1",
    "vue": "^3.2.45",
    "vue-router": "^4.1.6"
  },
```

// md.vue
```vue
<template>
  <div>
    <!-- <Viewer :value="content" :plugins="plugins"></Viewer> -->
    <Editor v-model="content" :plugins="plugins"></Editor>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
// @ts-ignore
import { Editor, Viewer } from '@bytemd/vue-next'
import 'bytemd/dist/index.css'
import gfm from '@bytemd/plugin-gfm'
import highlight from '@bytemd/plugin-highlight'
import math from '@bytemd/plugin-math'

const content = ref('')
const plugins = [gfm(), highlight(), math()]
</script>
```

**Comment by CPunisher** [comment]
按照 vue3 的 example: https://github.com/bytedance/bytemd/blob/main/examples/vue3/src/App.vue
把 `<Editor>` 上的 `v-model` 改成 `:value` 和 `@change`

**Comment by kvchen95** [comment]
> 按照 vue3 的 example: https://github.com/bytedance/bytemd/blob/main/examples/vue3/src/App.vue 把 `<Editor>` 上的 `v-model` 改成 `:value` 和 `@change`

thanks！

**Comment by darkchan** [comment]
我单独引用Viewer组件，上面的编辑组件样式生效了，但是下方的Viewer组件样式有部分不生效（比如代码的背景色）
![1687224263395](https://github.com/bytedance/bytemd/assets/23554613/f69c37c3-b1eb-48cc-b0f4-d8f025651101)
请问是怎么回事呢？源码如下图：
![1687224147923](https://github.com/bytedance/bytemd/assets/23554613/1b666a6c-cd42-4079-9ef1-7a465ffa7d9d)
