### ISSUE TITLE
Tailwind's reset wrecking the toolbar

### ISSUE THREAD

**Issue by individual11** [pd4d10/hashmd#282]
<img width="1381" alt="Screenshot 2023-03-08 at 1 30 35 PM" src="https://user-images.githubusercontent.com/612598/223803532-82469574-6ffe-4ffa-a731-4648c53c6833.png">

I have a tailwind `unset` class that forces the reset back, but I can't quite figure out how to get it into the editor. The viewer works/looks perfect.

Any thoughts?

**Comment by pd4d10** [comment]
Could you please provide a minimal reproduction?
