### ISSUE TITLE
更新到v1.20.2，点击icon上传图片会报错，如下图所示。粘贴或者拖拽图片到编辑器中可以正常使用

### ISSUE THREAD

**Issue by jinyu-zhixuan** [pd4d10/hashmd#283]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/55437866/225256697-e0ac1d5e-dc21-45ee-9a06-624321b031ba.png">

**Comment by jinyu-zhixuan** [comment]
补充说明  当前引用的是vue版本的编辑器  项目vue版本为2.7.14  

之前引用的编辑器是1.15.0

**Comment by CPunisher** [comment]
重复了: https://github.com/bytedance/bytemd/issues/279
我试着新建了一个 vue2 项目也没复现出来，可能是升级之后缺 select-files 这个依赖了？
尝试卸载 bytemd 和 @bytemd/vue 之后重新安装看看？

**Comment by 15079698746** [comment]
> 

重新安装还是报错
