### ISSUE TITLE
Editor wont work in SvelteKit

### ISSUE THREAD

**Issue by redii** [pd4d10/hashmd#284]
Hello, first I want to say that the module is great and I really want to use it but after I installed the package (v1.20.2 and in previous versions) I get the error shown in the screenshot below. Even the Editor without value, plugins and onchange handler does not work and throws the same error.

<img width="1007" alt="Screenshot 2023-03-20 at 12 56 22" src="https://user-images.githubusercontent.com/14221837/226332359-2ea4536c-179f-4057-89e1-aa3128e67591.png">

<img width="462" alt="Screenshot 2023-03-20 at 12 56 50" src="https://user-images.githubusercontent.com/14221837/226332456-61998ada-c19d-4c8b-8dac-da3c970a027d.png">

<img width="398" alt="Screenshot 2023-03-20 at 12 59 35" src="https://user-images.githubusercontent.com/14221837/226333018-720a3f11-fcf2-4219-98c1-94627dae0296.png">

**Comment by seo-rii** [comment]
Duplicate of #269.
