### ISSUE TITLE
The left edit area is not displayed on the first render. Click to get focus

### ISSUE THREAD

**Issue by xbw19975** [pd4d10/hashmd#286]
The version I use: @bytemd/react v1.20.2
My component code:`
import { Editor, Viewer } from '@bytemd/react';
import gfm from '@bytemd/plugin-gfm';
import 'bytemd/dist/index.css';

const ByteMD = (props: ByteMDProps): any => {
  const { value, onChange = () => undefined, Height = '300px', className, readonly } = props;

  const defaultSettings = {
    locale: zh_Hans,
    plugins,
  };

  return (
    <div style={{ height: Height }}>
      {readonly ? (
        <Viewer value={value} {...defaultSettings} />
      ) : (
        <Editor value={value} onChange={onChange} {...defaultSettings}></Editor>
      )}
    </div>
  );
};

export default ByteMD;`
Detailed description of the problem: The first time I open the page,value has an initial value. But only the value is displayed in the right preview area. There is no default value displayed in the left edit area. It only shows when I click on the left edit area. This only happens when the page is rendered for the first time. How can I solve this situation? I find that the first value is actually passed into the component

Map as follows:
![image](https://user-images.githubusercontent.com/46275212/226859450-07b83021-afba-452b-a479-43f14fdd467e.png)
After click
![image](https://user-images.githubusercontent.com/46275212/226859721-bfd1f8f9-07b7-4447-b535-eacab5054a3e.png)

**Comment by pd4d10** [comment]
Could you please provide a minimal reproduction?

**Comment by xbw19975** [comment]
Do you mean how it is used?

Examples are as follows:

`const DescriptionModal: React.FC<APIDescriptionProps> = (props) => {
  const { value = '', onChange, onCancel, title } = props;
  const readonly = useSelector((store) => store?.user?.readonly);

  return (
    <Modal title={title || '接口说明'} visible onCancel={onCancel} footer={null}>
      <Markdown Height="500px" value={value} onChange={onChange} readonly={readonly == 1} />
    </Modal>
  );
};`
