### ISSUE TITLE
滚动时有显示Bug

### ISSUE THREAD

**Issue by Youky1** [pd4d10/hashmd#288]
触发条件：

- 左侧md源码长度不够滚动
- 右侧显示内容已足够滚动
- 鼠标放在右侧内容区滚动

结果：左侧源码区域上面的一部分不显示（变为了空白）

![image](https://user-images.githubusercontent.com/56068056/228510341-52f4e971-506a-454b-b7e1-a6fdffc5409b.png)

**Comment by CPunisher** [comment]
这是应该是下游产品的bug，在最新的 bytemd playground 中不会出现  https://bytemd.js.org/playground/

**Comment by Youky1** [comment]
这个是掘金的闪念笔记页面，那可能是他们的二次封装有bug

**Comment by CPunisher** [comment]
可以考虑去掘金社区发用户反馈
