### ISSUE TITLE
math 无法使用 latex 多行显示

### ISSUE THREAD

**Issue by carveybunt** [pd4d10/hashmd#292]
```vue
const plugins = [
  gfm(),
  math({
    locale: mathLocal,
    katexOptions: { output: 'html' },
  }),
  highlight(),
]
```
```vue
<Editor :value="modelValue" :plugins="plugins" :locale="zhHans" @change="change" />
```
![截屏2023-04-03 11 52 48](https://user-images.githubusercontent.com/37894474/229407661-9149d73a-cedb-4d58-ac31-124d23d0c4b6.png)

单行模式没问题。

```json
vue: 3.2.47
@bytemd/vue-next: 1.21.0
```

**Comment by CPunisher** [comment]
https://katex.org/docs/supported.html#environments 
上游 katex 支持的 environment 有限，看看有没有平替？
