### ISSUE TITLE
与arco组件库进行配合使用时，全屏会出现样式问题

### ISSUE THREAD

**Issue by FatDoge** [pd4d10/hashmd#293]
详见这个demo：https://codesandbox.io/s/amazing-sunset-w33i1e?file=/src/App.tsx
里面穿插了不同的表单项组件，点击里面的编辑器全屏，会有样式问题，有的表单项不会隐藏。

**Comment by CPunisher** [comment]
看起来是全屏的时候被表单组件遮挡了，尝试增加 `z-index` 或者在层叠上下文里做一些文章？
