### ISSUE TITLE
tel not rendering correctly

### ISSUE THREAD

**Issue by davidh10** [pd4d10/hashmd#298]
If you write
`<a href="tel:+4733378901">+47 333 78 901</a>`

It renders as:
`<p><a>+47 333 78 901</a></p>`

Instead of: 
`<p><a href="tel:+4733378901">+47 333 78 901</a></p>`

However mailto works fine.
`<a href="mailto:email@example.com">Send Email</a>`

**Comment by CPunisher** [comment]
Maybe it's also blocked by `rehype-sanitize`. See:
https://github.com/bytedance/bytemd/issues/299
https://github.com/syntax-tree/hast-util-sanitize/blob/main/lib/schema.js#L21
