### ISSUE TITLE
iframe not working

### ISSUE THREAD

**Issue by davidh10** [pd4d10/hashmd#299]
Hi, I migrated over to bytemd from another markdown editor but noticed that bytemd doesn't render iframes (youtube videos). Is this a bug or how can I solve this issue?

```
## Hello world

<iframe width="420" height="315"
src="https://www.youtube.com/embed/tgbNymZ7vqY">
</iframe>
```

**Comment by CPunisher** [comment]
`<iframe>` will be removed by `rehype-sanitize` with default schema. See: 
https://github.com/bytedance/bytemd/blob/main/packages/bytemd/src/utils.ts#L38
https://github.com/syntax-tree/hast-util-sanitize

You can custom your sanitizing function using `sanitize` props.
