### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by TIOvOIT** [pd4d10/hashmd#3]
我在Sapper中使用 bytemd ，将之引入组件内，编译时提示以下错误：

> xxx\node_modules\codemirror\lib\codemirror.js:18
>   var userAgent = navigator.userAgent;
> 
> **ReferenceError: navigator is not defined**
>     at xxx\node_modules\codemirror\lib\codemirror.js:18:19
>     at userAgent (D:\cloud\frontend\node_modules\codemirror\lib\codemirror.js:11:83)
>     at Object.<anonymous> (D:\cloud\frontend\node_modules\codemirror\lib\codemirror.js:14:2)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)

项目所使用的依赖CodeMirror无法在SSR环境中运行，故尝试：

> onMount(async () => {
>     const { Editor } = await import("bytemd")
>     new Editor({
>       target: document.getElementById("editor")
>     });
>   });

亦报错：

> Uncaught (in promise) TypeError: Failed to resolve module specifier "path". Relative references must start with either "/", "./", or "../".

相关程序版本：

>    "rollup": "^1.20.0",
>    "svelte": "^3.22.0",
>    "sapper": "^0.27.12",
>    "bytemd": "0.0.11",

还望解决。

**Comment by pd4d10** [comment]
Hi, @TIOvOIT 感谢反馈

> ReferenceError: navigator is not defined

这个问题现在应该已经解决了。可以试试最新版本。另外，也不需要在业务代码中 dynamic import，在组件内部已经处理好

> Failed to resolve module specifier "path"

这个可能需要引入 [rollup-plugin-node-globals](https://github.com/calvinmetcalf/rollup-plugin-node-globals) 和 [rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins) 来正确地处理某些依赖使用的 Node.js 内置模块
