### ISSUE TITLE
中文输入时内容被输入法弹窗遮盖问题

### ISSUE THREAD

**Issue by HoPGoldy** [pd4d10/hashmd#307]
# 问题

在输入中文时，正在输入的内容会被输入法的补全弹窗遮盖，影响使用体验：

![image](https://github.com/bytedance/bytemd/assets/28479777/ba7381d4-954d-42aa-85cd-e8fd4c055fb1)

# 如何复现

[playground](https://bytemd.js.org/playground/) 和 [掘金文章编辑器](https://juejin.cn/editor/drafts/new?v=2) 均存在该问题。

操作系统：win10 / win11

# 期望

正在输入的文字可以正常显示出来：

![image](https://github.com/bytedance/bytemd/assets/28479777/03aa2779-306d-478f-acf3-9f9f325dbfd9)

**Comment by jianchuxin** [comment]
确实，我也有这个问题，咋还没解决
