### ISSUE TITLE
希望完善文档，文档太简陋了，编辑器的配置项都没列出来

### ISSUE THREAD

**Issue by fxzer** [pd4d10/hashmd#321]

**Comment by fxzer** [comment]
editorConfig可配置项

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f3b3be99b304f5049338884c70d49a41d39730c2/types/codemirror/index.d.ts#L1240

**Comment by CodeGetters** [comment]
请问 Viewr 可配置项在哪啊 怎么设置 bytemd-toolbar 这一栏的一些东西默认点击 比如说我想要 Editor 默认选择(preview only 和 点击 Table of contents-目录)❓
