### ISSUE TITLE
How to get catalog

### ISSUE THREAD

**Issue by WinmezzZ** [pd4d10/hashmd#33]
Any  get catalog api had been exported? I saw catelog in editor toolbar, but how can I get catalog without editor? Just like in a post detail page.

My html string get by `getProcessor` api, it imported from `bytemd`, so I want to ask that did you exported get catelog api like `getProcessor`.

Thanks.

**Comment by pd4d10** [comment]
The TOC is extracted from the hast syntax tree:

```js
import { getProcessor } from 'bytemd'

let hast
getProcessor({
  plugins: [
    {
      rehype: (p) =>
        p.use(() => (tree) => {
          hast = tree
        }),
    },
  ],
}).processSync(value);

console.log(hast) // h1-h6 is what you want
```
