### ISSUE TITLE
Feature/Design Guideline: 设计不搭 Design are not following the same guideline

### ISSUE THREAD

**Issue by PassionPenguin** [pd4d10/hashmd#46]
<img width="1175" alt="Screen Shot 2021-03-10 at 8 01 08 PM" src="https://user-images.githubusercontent.com/41184947/110626181-61966800-81db-11eb-9c65-1959e9322471.png">

https://bytemd.netlify.app/

Top toolbar's icons are not the same style, and the first three icons should be smaller, eg GitHub Editor is much better:

<img width="469" alt="Screen Shot 2021-03-10 at 8 02 42 PM" src="https://user-images.githubusercontent.com/41184947/110626351-94406080-81db-11eb-9aa5-c1b46e18b002.png">

**Comment by pd4d10** [comment]
Thanks for the feedback. Icons are taken from [IconPark](https://github.com/bytedance/iconpark). Do you have other suggestions?

**Comment by PassionPenguin** [comment]
nope....it's fine but just a little bit weird
