### ISSUE TITLE
Is there a plan to use rightActions as an option here

### ISSUE THREAD

**Issue by shfshanyue** [pd4d10/hashmd#53]
Is there a plan to use toolbar actions as an option here，eg. fullscreen, help, toc, previewOnly and so on. 

Or it's possible to extend actions

**Comment by pd4d10** [comment]
Do you mean adding or deleting the right toolbar actions?

If the purpose is to delete items,  perhaps `display:none` with CSS is an option.

**Comment by shfshanyue** [comment]
thx
