### ISSUE TITLE
可以添加针对大量主题和样式的搜索功能和回显功能吗

### ISSUE THREAD

**Issue by FrankWangCN** [pd4d10/hashmd#54]
目前新版功能中添加了主题选择功能，但是由于数量较多，每次使用如果要更换主题都需要向下翻阅大量选项，希望能添加主题的**关键字搜索功能**和**回显**当前选中主题的功能

**Comment by shfshanyue** [comment]
新版功能的主题并不是 bytemd 的功能，而是掘金开发的一个 bytemd 插件，可以用来更换多套皮肤，而这个插件貌似并没有开源，所以这个问题可以问问掘金官方

**Comment by pd4d10** [comment]
主题功能还在迭代中，稳定之后可以抽取为 plugin

**Comment by FrankWangCN** [comment]
> 主题功能还在迭代中，稳定之后可以抽取为 plugin
好的，了解，非常感谢

**Comment by PassionPenguin** [comment]
挺赞同的
