### ISSUE TITLE
可以有上传图片和自定义添加导航栏选项的功能吗？

### ISSUE THREAD

**Issue by qklhk** [pd4d10/hashmd#55]

**Comment by qklhk** [comment]
这个问题对于我来说非常重要。

**Comment by pd4d10** [comment]
Upload images: https://github.com/bytedance/bytemd/issues/23#issuecomment-787473034

**Comment by pd4d10** [comment]
> 自定义添加导航栏选项

有的，文档近期会补充上去。
Duplicate of #50
