### ISSUE TITLE
源码里是用了dynamic import ?

### ISSUE THREAD

**Issue by Aaronphy** [pd4d10/hashmd#58]
发现打包出来的时候多了一份chunk文件

**Comment by pd4d10** [comment]
无需 SSR 的版本是前端渲染的，懒加载可以减少首屏体积

如果需要打成一个包，可以配置一下打包工具，或者使用 SSR 版本

**Comment by Aaronphy** [comment]
> 无需 SSR 的版本是前端渲染的，懒加载可以减少首屏体积
> 
> 如果需要打成一个包，可以配置一下打包工具，或者使用 SSR 版本

我配置了，但是没用。。。不知道咋处理了
