### ISSUE TITLE
markdown parsing problem

### ISSUE THREAD

**Issue by PassionPenguin** [pd4d10/hashmd#64]
see attachment
<img width="1621" alt="Screenshot 2021-03-22 at 1 15 00 AM" src="https://user-images.githubusercontent.com/41184947/111914228-1cf8af80-8aac-11eb-9433-56af4ef8c68d.png">

it should not be highlighted for the rest of the code in the editor, just like the rendering area on the right side

well in github:

> ```markdown
> 首先，先在我们的编辑器中输入 **```mermaid**，然后敲一下回车键，在包含的代码段中输入 Mermaid 代码就可以使用 Mermaid > 啦～
> ```
> 
> 首先，先在我们的编辑器中输入 **```mermaid**，然后敲一下回车键，在包含的代码段中输入 Mermaid 代码就可以使用 Mermaid 啦～

it works well~

<img width="863" alt="Screenshot 2021-03-22 at 1 16 52 AM" src="https://user-images.githubusercontent.com/41184947/111914269-4c0f2100-8aac-11eb-80a8-ced31f1e6bc2.png">

**Comment by PassionPenguin** [comment]
well it's even worse:

<img width="767" alt="Screenshot 2021-03-22 at 1 19 33 AM" src="https://user-images.githubusercontent.com/41184947/111914420-d192d100-8aac-11eb-863a-a39f79b366b9.png">

> ```markdown
> # 看起来好复杂的 🦆
> 
> * 你：我会了
> * 🦆：我不活了
> 
> 首先，先在我们的编辑器中输入 **```mermaid**，然后敲一下回车键，在包含的代码段中输入 Mermaid 代码就可以使用 Mermaid 啦～
> 
> ## 流程图
> 
> 语法解释：graph 关键字就是声明一张流程图，TD 表示的是方向，这里的含义是 Top-Down 由上至下。
> 
> graph TD;
>     A-->B;
>     A-->C;
>     B-->D;
> ```
> 
> # 看起来好复杂的 🦆
> 
> * 你：我会了
> * 🦆：我不活了
> 
> 首先，先在我们的编辑器中输入 **```mermaid**，然后敲一下回车键，在包含的代码段中输入 Mermaid 代码就可以使用 Mermaid 啦～
> 
> ## 流程图
> 
> 语法解释：graph 关键字就是声明一张流程图，TD 表示的是方向，这里的含义是 Top-Down 由上至下。
> 
> graph TD;
>     A-->B;
>     A-->C;
>     B-->D;

**Comment by pd4d10** [comment]
It seems to be the issue of CodeMirror's syntax highlight.
