### ISSUE TITLE
Styling words in the Viewer

### ISSUE THREAD

**Issue by kimaldis** [pd4d10/hashmd#72]
I'm working on notebook app using svelte in Electron and I'm looking at how to turn hashtags in the Editor view into  styled, highlighted links in the Viewer view. What I think I'd like to do, and someone may have a better way, is to catch text somewhere in the render process, grep hashtags and wrap them in HTML. Thoughts appreciated, thanks.

<img width="218" alt="Screenshot 2021-03-28 at 09 14 29" src="https://user-images.githubusercontent.com/4265299/112746355-1388af00-8fa6-11eb-8ece-c122ce27ffee.png">

**Comment by pd4d10** [comment]
Another approach is to use [remark plugin](https://github.com/remarkjs/remark/blob/main/doc/plugins.md) to transform the customized Markdown syntax to the HTML you want.
