### ISSUE TITLE
Can't close view of image link

### ISSUE THREAD

**Issue by kimaldis** [pd4d10/hashmd#73]
I've added a link to a document that points to an image. I click on it in the Viewer and it fills my app window. This is fine, except I can't find a way to close the image beyond shutting down the app.

**Comment by PassionPenguin** [comment]
it should be closed once you clicked the window frame……

works fine for me on Chrome 91

**Comment by kimaldis** [comment]
Forgot to mention, I'm using Electron, MacOS

**Comment by pd4d10** [comment]
Looks like it's the default behavior of the browser...
