### ISSUE TITLE
Support for inserting external image 

### ISSUE THREAD

**Issue by bobbui** [pd4d10/hashmd#76]
It seems that the editors only provide a function to upload image and then get back the URL to insert into the markdown document. Could you please consider a feature that allow user to insert an external image URL?

Thanks in advance!

**Comment by pd4d10** [comment]
If you already have the external image URL, You could just use Markdown syntax:

```md
![alt](url)
```

**Comment by bobbui** [comment]
@pd4d10 thanks for your answer, my point is actually a button for that on toolbar would be very convenient.
