### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by mivinci** [pd4d10/hashmd#87]
I am using bytemd in a SvelteKit app and errors occurred
![image](https://user-images.githubusercontent.com/33592375/115976578-f1348200-a5a1-11eb-9bf2-fc499b67b332.png)
![image](https://user-images.githubusercontent.com/33592375/115976581-fb568080-a5a1-11eb-9cce-a5c39b5a6af6.png)

Seems like Vite doesn't support CommonJS modules that bytemd imported. Has anyone encountered this situation or should I go [SvelteKit](https://github.com/sveltejs/kit) and [Vite](https://github.com/vitejs/vite) for help?

**Comment by mivinci** [comment]
Most likely it's a bug caused by SvelteKit's builtin Vite but I'm curious if anyone solved this problem in their SvelteKit apps.

**Comment by pd4d10** [comment]
We have an example here https://github.com/bytedance/bytemd/blob/main/examples/svelte-kit/README.md

But there seems a little problem with the SSR process.

**Comment by mivinci** [comment]
@pd4d10 Yep. I've tried to disable SSR both app-wide and on page-level according to https://kit.svelte.dev/docs#ssr-and-javascript-ssr but they didn't work for me. Finally, I found this error disappeared when previewing bundled version with sveltekit's node-adapter. 
It is just Vite's problem I guess cuz a lot of people got the situation there https://github.com/vitejs/vite/issues?q=require+is+not+defined

**Comment by MarcGodard** [comment]
@Mivinci Did you get it working? Having the same problem.

**Comment by CaptainCodeman** [comment]
> We have an example here https://github.com/bytedance/bytemd/blob/main/examples/svelte-kit/README.md
> 
> But there seems a little problem with the SSR process.

The problem with that example is that it is using WebPack to create a separate package that the example then imports. This isn't how most users of SvelteKit are going to try to consume the package.

**Comment by ohsofoxy273** [comment]
_Sometimes_ I can fix this error by not importing as `import {things} from 'thePackage'`, and instead import as `import * as WhateverName from 'thePackage'`, then declare `const {things} = WhateverName`
