### ISSUE TITLE
能不能把所有的功能都做成插件形式

### ISSUE THREAD

**Issue by Lu-HuaiLiang** [pd4d10/hashmd#90]
有时候真的不需要H标题，这个功能。
很想删掉H按钮，和不让markdown解析#号

**Comment by zheeeng** [comment]
fork 一下就好了

**Comment by pd4d10** [comment]
> 不需要H标题

工具栏定制目前确实还没有支持删除按钮，可以考虑加上

> 不让markdown解析#号

这个可以自行添加 remark plugin 来实现
