### ISSUE TITLE
Allow custom React components for @bytemd/react

### ISSUE THREAD

**Issue by loredanacirstea** [pd4d10/hashmd#91]
I wanted to use https://github.com/rjantoine/react-markdown-remark-directive, but I can't find a place to hook the rendering of custom React components.

I see that `rehype-stringify` is used, so the markdown AST never goes through React, but through html, so what I want might not be possible now.
If you see a way, give me a pointer.

**Comment by pd4d10** [comment]
> the markdown AST never goes through React, but through html

Yeah, the original design of ByteMD is framework agnostic, so it's important to not couple it with the React runtime. The React component is just a simple wrapper of the Svelte version.

I guess [MDX](https://mdxjs.com/) may be the solution you want

**Comment by loredanacirstea** [comment]
I ended up using other tools. Closing this issue.
I have actually built my own interpreted language for UI components, which works well with Markdown.
