### ISSUE TITLE
Pasting images in Quotes leads to incorrect positioning

### ISSUE THREAD

**Issue by PassionPenguin** [pd4d10/hashmd#93]
with image in pasteboard, paste the image in a quote `> ...`, and after the uploading, the image tag will be placed at the nearest non-quote paragraph.

(+: with cursor in quote paragraph, use the button to upload images leads to the same result)

**Comment by pd4d10** [comment]
> with image in pasteboard, paste the image in a quote `> ...`, and after the uploading, the image tag will be placed at the nearest non-quote paragraph.

Yeah, it's by design currently. The image always goes to the next paragraph. Source code here:

https://github.com/bytedance/bytemd/blob/d615c5f9b5f233dd98b80284816405c6b09e3bc6/packages/bytemd/src/editor.ts#L125-L141

We can discuss if there is a better strategy

**Comment by PassionPenguin** [comment]
>> with image in pasteboard, paste the image in a quote `> ...`, and after the uploading, the image tag will be placed at the nearest non-quote paragraph.
> 
> Yeah, it's by design currently. The image always goes to the next paragraph. Source code here:
> 
> https://github.com/bytedance/bytemd/blob/d615c5f9b5f233dd98b80284816405c6b09e3bc6/packages/bytemd/src/editor.ts#L125-L141
> 
> We can discuss if there is a better strategy

adding an extra condition statement to force adding the image into the quote instead of the next para. may be better? since uploading images and paste them in the quote is commonly used in some news reports.

**Comment by pd4d10** [comment]
Sounds good. Would you like to send a PR?

**Comment by PassionPenguin** [comment]
> Sounds good. Would you like to send a PR?

thx but i am not familiar with it.... thx anyway

**Comment by pd4d10** [comment]
Never mind. We can keep it open for further discussion
