### ISSUE TITLE
Extracting rendered content?

### ISSUE THREAD

**Issue by vha14** [pd4d10/hashmd#94]
The markdown content is `value` which is easily accessible. How can I access the rendered content (`previewEl`?). The goal is to submit both markdown content and the rendered content to a backend service.

Thanks!

**Comment by vha14** [comment]
My hacky attempt:

```js
const editorRef = useRef()
...
const onSubmit = () => {
    console.log(editorRef.current.getElementsByClassName('markdown-body')[0])
}

...
return (
    <div ref={editorRef}>
         <Editor ... />
    </div>
)

**Comment by pd4d10** [comment]
The proposed way is to save the markdown content and use the `Viewer` component where you want to display it. 

The HTML content may be different with different plugins. It would be better to make markdown the single source of truth

**Comment by pd4d10** [comment]
If you just want to process the markdown -> HTML with the same behavior of ByteMD, there is a `getProcessor` exposed to do this:

```js
import { getProcessor } from 'bytemd'

getProcessor({
  plugins: [] // use plugins here
}).processSync('# markdown text')
```
