### ISSUE TITLE
TOC中的heading为何会生成带有“user-content”的前缀？

### ISSUE THREAD

**Issue by aidoit** [pd4d10/hashmd#95]
`<div data-v-b866336a="" class="markdown-body"><h3 id="user-content-test1">test 1</h3>
`
导致锚点定位功能失效。

**Comment by pd4d10** [comment]
It's for sanitize purposes, see https://github.com/syntax-tree/hast-util-sanitize#clobberprefix

You can use the `Viewer` component which handles it correctly.

**Comment by pd4d10** [comment]
Closing, feel free to reopen it if there are other issues
